/* Generated by eXtremeDB Schema Compiler, build 1797, rev. stable, rev. 23320
 * at Wed Jan  2 19:26:16 2019
 */

#include "genericdb.h"
#include "mcowrap.h"


/*---------------------------------------------------------------------*/
/* calculator                                                          */

mco_calculator_h genericdb_get_calculator(void)
{
  return (mco_calculator_h)NULLPTR;
}


/*---------------------------------------------------------------------*/
/* dictionary                                                          */

static mco_dictionary_t  dict; 
mco_dictionary_h genericdb_get_dictionary(void)
{ 
  static int dictionary_ready = 0; 

  if( ! dictionary_ready ) 
  {
    static mco_dict_field_t v_field_info[66] = { 
    /* Dimensions */
    {"height", {4, 4, 4, 4, 4, 4}, 10, 0, 0, -1, 4, -1, 0, 2, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    {"length", {4, 4, 0, 4, 4, 0}, 10, 0, 0, -1, 4, -1, 0, 1, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    {"width", {4, 4, 8, 4, 4, 8}, 10, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    /* A */
    {"ui4", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 1 */},
    /* B */
    {"ui4", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 2 */},
    /* Part */
    {"code", {4, 4, 44, 4, 4, 8}, 3, 8, 0, -1, 4, -1, 0, 3, 3, 65535, 65535, 0, 0, 0 /* 7 */},
    {"dim", {12, 4, 48, 12, 4, 12}, 50, 0, 0, 0, 0, -1, 0, 4, 4, 65535, 65535, 0, 0, 0 /* 8 */},
    {"name", {2, 2, 60, 4, 4, 0}, 8, 8, 0, -1, 0, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 5 */},
    {"options", {40, 4, 0, 40, 4, 24}, 3, 2, 10, -1, 4, -1, 0, 5, 5, 65535, 65535, 0, 0, 0 /* 9 */},
    {"price", {4, 4, 40, 4, 4, 4}, 10, 0, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 6 */},
    {"type", {2, 2, 62, 4, 4, 64}, 8, 8, 0, -1, 0, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 4 */},
    /* Part2 */
    {"broker_id", {4, 4, 0, 4, 4, 0}, 6, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 10 */},
    {"password", {8, 1, 8, 8, 1, 8}, 7, 0, 0, -1, 8, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 11 */},
    {"user_id", {4, 4, 4, 4, 4, 4}, 3, 8, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 12 */},
    /* User */
    {"broker_id", {4, 4, 4, 4, 4, 4}, 6, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 13 */},
    {"password", {8, 1, 8, 8, 1, 8}, 7, 0, 0, -1, 8, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 15 */},
    {"user_id", {4, 4, 0, 4, 4, 0}, 3, 8, 0, -1, 4, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 14 */},
    /* OrderInsert */
    {"bs_flag", {1, 1, 55, 1, 1, 57}, 1, 0, 0, -1, 1, -1, 0, 9, 9, 65535, 65535, 0, 0, 0 /* 25 */},
    {"business_code", {4, 4, 16, 4, 4, 0}, 6, 0, 0, -1, 4, -1, 0, 10, 10, 65535, 65535, 0, 0, 0 /* 26 */},
    {"exchange_type", {1, 1, 56, 1, 1, 58}, 1, 0, 0, -1, 1, -1, 0, 8, 8, 65535, 65535, 0, 0, 0 /* 24 */},
    {"front_id", {4, 4, 32, 4, 4, 8}, 6, 0, 0, -1, 4, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 17 */},
    {"investor_id", {4, 4, 4, 4, 4, 4}, 6, 0, 0, -1, 4, -1, 0, 5, 5, 65535, 65535, 0, 0, 0 /* 21 */},
    {"order_ref", {4, 4, 36, 4, 4, 36}, 6, 0, 0, -1, 4, -1, 0, 3, 3, 65535, 65535, 0, 0, 0 /* 19 */},
    {"owner_type", {2, 2, 40, 2, 2, 44}, 2, 0, 0, -1, 2, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 16 */},
    {"price", {8, 4, 24, 8, 4, 24}, 13, 128, 0, -1, 8, -1, 0, 12, 12, 65535, 65535, 3, 0, 0 /* 28 */},
    {"price_type", {1, 1, 54, 1, 1, 56}, 1, 0, 0, -1, 1, -1, 0, 11, 11, 65535, 65535, 0, 0, 0 /* 27 */},
    {"secu_account", {10, 1, 44, 10, 1, 46}, 7, 0, 0, -1, 10, -1, 0, 6, 6, 65535, 65535, 0, 0, 0 /* 22 */},
    {"security_code", {2, 2, 42, 4, 4, 32}, 8, 0, 0, -1, 0, -1, 0, 7, 7, 65535, 65535, 0, 0, 0 /* 23 */},
    {"session_id", {4, 4, 20, 4, 4, 20}, 6, 0, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 18 */},
    {"user_id", {4, 4, 0, 4, 4, 40}, 6, 0, 0, -1, 4, -1, 0, 4, 4, 65535, 65535, 0, 0, 0 /* 20 */},
    {"volume", {8, 4, 8, 8, 4, 12}, 12, 0, 0, -1, 8, -1, 0, 13, 13, 65535, 65535, 0, 0, 0 /* 29 */},
    /* Order */
    {"amount_traded", {8, 4, 16, 8, 4, 12}, 13, 128, 0, -1, 8, -1, 0, 20, 20, 65535, 65535, 2, 0, 0 /* 50 */},
    {"branch_id", {4, 4, 12, 4, 4, 0}, 6, 0, 0, -1, 4, -1, 0, 14, 14, 65535, 65535, 0, 0, 0 /* 44 */},
    {"bs_flag", {1, 1, 79, 1, 1, 81}, 1, 0, 0, -1, 1, -1, 0, 9, 9, 65535, 65535, 0, 0, 0 /* 39 */},
    {"business_code", {4, 4, 48, 4, 4, 44}, 6, 0, 0, -1, 4, -1, 0, 10, 10, 65535, 65535, 0, 0, 0 /* 40 */},
    {"exchange_type", {1, 1, 91, 1, 1, 93}, 1, 0, 0, -1, 1, -1, 0, 8, 8, 65535, 65535, 0, 0, 0 /* 38 */},
    {"front_id", {4, 4, 40, 4, 4, 8}, 6, 0, 0, -1, 4, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 31 */},
    {"investor_id", {4, 4, 52, 4, 4, 48}, 6, 0, 0, -1, 4, -1, 0, 5, 5, 65535, 65535, 0, 0, 0 /* 35 */},
    {"order_exchange_id", {10, 1, 81, 10, 1, 83}, 7, 0, 0, -1, 10, -1, 0, 17, 17, 65535, 65535, 0, 0, 0 /* 47 */},
    {"order_ref", {4, 4, 28, 4, 4, 28}, 6, 0, 0, -1, 4, -1, 0, 3, 3, 65535, 65535, 0, 0, 0 /* 33 */},
    {"order_sys_id", {10, 1, 92, 10, 1, 94}, 7, 0, 0, -1, 10, -1, 0, 16, 16, 65535, 65535, 0, 0, 0 /* 46 */},
    {"owner_type", {2, 2, 64, 2, 2, 68}, 2, 0, 0, -1, 2, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 30 */},
    {"pbu_id", {4, 4, 8, 4, 4, 4}, 6, 0, 0, -1, 4, -1, 0, 15, 15, 65535, 65535, 0, 0, 0 /* 45 */},
    {"price", {8, 4, 56, 8, 4, 52}, 13, 128, 0, -1, 8, -1, 0, 12, 12, 65535, 65535, 3, 0, 0 /* 42 */},
    {"price_type", {1, 1, 78, 1, 1, 80}, 1, 0, 0, -1, 1, -1, 0, 11, 11, 65535, 65535, 0, 0, 0 /* 41 */},
    {"secu_account", {10, 1, 68, 10, 1, 70}, 7, 0, 0, -1, 10, -1, 0, 6, 6, 65535, 65535, 0, 0, 0 /* 36 */},
    {"security_code", {2, 2, 66, 4, 4, 24}, 8, 0, 0, -1, 0, -1, 0, 7, 7, 65535, 65535, 0, 0, 0 /* 37 */},
    {"session_id", {4, 4, 24, 4, 4, 20}, 6, 0, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 32 */},
    {"status", {1, 1, 80, 1, 1, 82}, 1, 0, 0, -1, 1, -1, 0, 18, 18, 65535, 65535, 0, 0, 0 /* 48 */},
    {"user_id", {4, 4, 44, 4, 4, 40}, 6, 0, 0, -1, 4, -1, 0, 4, 4, 65535, 65535, 0, 0, 0 /* 34 */},
    {"volume", {8, 4, 0, 8, 4, 60}, 12, 0, 0, -1, 8, -1, 0, 13, 13, 65535, 65535, 0, 0, 0 /* 43 */},
    {"volume_traded", {8, 4, 32, 8, 4, 32}, 12, 0, 0, -1, 8, -1, 0, 19, 19, 65535, 65535, 0, 0, 0 /* 49 */},
    /* OrderAction */
    {"bs_flag", {1, 1, 50, 1, 1, 52}, 1, 0, 0, -1, 1, -1, 0, 11, 11, 65535, 65535, 0, 0, 0 /* 62 */},
    {"exchange_type", {1, 1, 71, 1, 1, 73}, 1, 0, 0, -1, 1, -1, 0, 7, 7, 65535, 65535, 0, 0, 0 /* 58 */},
    {"front_id", {4, 4, 32, 4, 4, 32}, 6, 0, 0, -1, 4, -1, 0, 3, 3, 65535, 65535, 0, 0, 0 /* 54 */},
    {"investor_id", {4, 4, 24, 4, 4, 24}, 6, 0, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 53 */},
    {"order_exchange_id", {10, 1, 61, 10, 1, 63}, 7, 0, 0, -1, 10, -1, 0, 8, 8, 65535, 65535, 0, 0, 0 /* 59 */},
    {"order_ref", {4, 4, 28, 4, 4, 28}, 6, 0, 0, -1, 4, -1, 0, 5, 5, 65535, 65535, 0, 0, 0 /* 56 */},
    {"order_sys_id", {10, 1, 40, 10, 1, 42}, 7, 0, 0, -1, 10, -1, 0, 6, 6, 65535, 65535, 0, 0, 0 /* 57 */},
    {"owner_type", {2, 2, 38, 2, 2, 40}, 2, 0, 0, -1, 2, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 51 */},
    {"price", {8, 4, 4, 8, 4, 16}, 13, 128, 0, -1, 8, -1, 0, 13, 13, 65535, 65535, 3, 0, 0 /* 64 */},
    {"secu_account", {10, 1, 51, 10, 1, 53}, 7, 0, 0, -1, 10, -1, 0, 9, 9, 65535, 65535, 0, 0, 0 /* 60 */},
    {"security_code", {2, 2, 36, 4, 4, 4}, 8, 0, 0, -1, 0, -1, 0, 10, 10, 65535, 65535, 0, 0, 0 /* 61 */},
    {"session_id", {4, 4, 20, 4, 4, 0}, 6, 0, 0, -1, 4, -1, 0, 4, 4, 65535, 65535, 0, 0, 0 /* 55 */},
    {"user_id", {4, 4, 0, 4, 4, 36}, 6, 0, 0, -1, 4, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 52 */},
    {"volume", {8, 4, 12, 8, 4, 8}, 12, 0, 0, -1, 8, -1, 0, 12, 12, 65535, 65535, 0, 0, 0 /* 63 */}
    };

    static mco_dict_struct_t v_struct_info[9] = { 
    { "Dimensions", 0, 3, (v_field_info + 0), 12, 4, 12, 4 },
    { "A", 0, 1, (v_field_info + 3), 4, 4, 4, 4 },
    { "B", 0, 1, (v_field_info + 4), 4, 4, 4, 4 },
    { "Part", 1, 6, (v_field_info + 5), 64, 4, 68, 4 },
    { "Part2", 0, 3, (v_field_info + 11), 16, 4, 16, 4 },
    { "User", 0, 3, (v_field_info + 14), 16, 4, 16, 4 },
    { "OrderInsert", 1, 14, (v_field_info + 17), 57, 4, 59, 4 },
    { "Order", 1, 21, (v_field_info + 31), 102, 4, 104, 4 },
    { "OrderAction", 1, 14, (v_field_info + 52), 72, 4, 74, 4 }
    };

    dictionary_ready = 1;

    {
      static const char * v_class_names[] = 
      {
        0, 
        "A"           , /* [1] */
        "B"           , /* [2] */
        "Part"        , /* [3] */
        "Part2"       , /* [4] */
        "User"        , /* [5] */
        "OrderInsert" , /* [6] */
        "Order"       , /* [7] */
        "OrderAction" , /* [8] */
        0
      };

      dict.str_class_names = v_class_names;
    }


    {
      static const char * v_index_names[] = 
      {
        "A.list_index_"           , /* [0] */
        "B.list_index_"           , /* [1] */
        "Part.ByCode"             , /* [2] */
        "Part.ByType"             , /* [3] */
        "Part.IdxCode"            , /* [4] */
        "Part2.IdxCode"           , /* [5] */
        "User.idx_user_id"        , /* [6] */
        0
      };

      dict.str_index_names = v_index_names;
    }

    {
      static  mco_dict_class_info_t class_inf[9] = { 
        { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, 
        { 0, 0, 0, -1, 4, 0, -1, 0, 0, -1, -2, 17, (v_struct_info + 1), 4, 0, 0 }  /* A */ , 
        { 1, 1, 1, -1, 4, 0, -1, 0, 0, -1, -2, 49, (v_struct_info + 2), 4, 0, 0 }  /* B */ , 
        { 2, 4, -1, -1, 0, 0, -1, 0, 0, -1, -2, 0, (v_struct_info + 3), 68, 0, 0 }  /* Part */ , 
        { 5, 5, -1, -1, 16, 0, -1, 0, 0, -1, -2, 16, (v_struct_info + 4), 16, 0, 0 }  /* Part2 */ , 
        { 6, 6, -1, -1, 16, 0, -1, 0, 0, -1, -2, 48, (v_struct_info + 5), 16, 0, 0 }  /* User */ , 
        { -1, -2, -1, -1, 0, 0, -1, 0, 0, -1, -2, 32, (v_struct_info + 6), 59, 0, 0 }  /* OrderInsert */ , 
        { -1, -2, -1, -1, 0, 0, -1, 0, 0, -1, -2, 32, (v_struct_info + 7), 104, 0, 0 }  /* Order */ , 
        { -1, -2, -1, -1, 0, 0, -1, 0, 0, -1, -2, 32, (v_struct_info + 8), 74, 0, 0 }  /* OrderAction */ 
      };
      dict.v_class_info = class_inf;
    }


    dict.v_desc_events = (mco_dict_event_t *)0;
    

    dict.v_all_struct = v_struct_info;
    {
      static mco_dict_index_field_t v_all_index_fields[ 6] = {
          { 8, -1, 4294967295U, 4, 3, 0, 3, -1 } /* [0] */
        , { 64, -1, 4294967295U, 0, 8, 0, 0, -1 } /* [1] */
        , { 0, -1, 4294967295U, 0, 8, 0, 1, -1 } /* [2] */
        , { 8, -1, 4294967295U, 4, 3, 0, 3, -1 } /* [3] */
        , { 4, -1, 4294967295U, 4, 3, 0, 2, -1 } /* [4] */
        , { 0, -1, 4294967295U, 4, 3, 0, 1, -1 } /* [5] */
      }; 

      static mco_dict_index_t v_all_indexes_info[ 7] = {
          { 1, 1, 0, -1, 1028, & v_all_index_fields[0], 0, -1 } /* A.list_index_ [0] */
        , { 2, 2, 0, -1, 1060, & v_all_index_fields[0], 0, -1 } /* B.list_index_ [1] */
        , { 3, 3, 1, -1, 2052, & v_all_index_fields[0], 10000, -1 } /* Part.ByCode [2] */
        , { 3, 1, 2, -1, 2048, & v_all_index_fields[1], 0, -1 } /* Part.ByType [3] */
        , { 3, 1, 1, -1, 2052, & v_all_index_fields[3], 0, -1 } /* Part.IdxCode [4] */
        , { 4, 1, 1, -1, 2052, & v_all_index_fields[4], 0, -1 } /* Part2.IdxCode [5] */
        , { 5, 2, 1, -1, 2084, & v_all_index_fields[5], 0, -1 } /* User.idx_user_id [6] */
      }; 

      dict.v_desc_indexes = v_all_indexes_info;
    }


    dict.v_desc_colls = (mco_dict_collation_t *)0;
    
    dict.version_major             = 8;
    dict.version_minor             = 0;
    dict.version_build             = 1797;
    dict.magic_number              = 9;
    dict.oid_is_supported          = 0;
    dict.auto_oid_supported        = 0;
    dict.flags                     = 0;
    dict.n_class_codes             = 8;
    dict.n_list_indexes            = 2;
    dict.n_autoid_indexes          = 0;
    dict.n_history_indexes         = 0;
    dict.n_userdef_indexes         = 0;
    dict.n_desc_indexes            = 7;
    dict.n_desc_events             = 0;
    dict.n_desc_colls              = 0;
    dict.n_structs                 = 9;
    dict.num_oid_estimation        = 0;
    dict.num_HA_estimation         = 0;
    dict.max_numof_indexes_per_obj = 3;
    dict.exact_OID_sizeof          = 0;
    dict.layout_OID_size           = 0;
    dict.sizeof_mco_offs_t[0]      = 4;
    dict.sizeof_mco_offs_t[1]      = sizeof(mco_offs_t);
    dict.sizeof_mco_size_t[0]      = 4;
    dict.sizeof_mco_size_t[1]      = sizeof(mco_size_t);
    dict.init_i_data.ptr           = 0;
    dict.init_i_data_n             = 0;
    dict.init_d_data.ptr           = 0;
    dict.init_d_data_n             = 0;
  }

  return &dict; 
}

MCO_RET      A_new                           ( mco_trans_h t, /*OUT*/ A *handle )
{ return mco_w_new_obj_noid( t, 4, 1, (mco_objhandle_h)handle);
}

MCO_RET      A_delete                        ( A *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      A_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 1 ); 
}

MCO_RET      A_checkpoint                    ( A *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      A_ui4_get                       ( A *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      A_ui4_put                       ( A *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      A_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ A *handle )
{ return mco_w_obj_from_cursor( t, c, 1, (mco_objhandle_h)handle ); 
}

MCO_RET      A_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_list_cursor( t, 1, c );
}

MCO_RET      B_new                           ( mco_trans_h t, /*OUT*/ B *handle )
{ return mco_w_new_obj_noid( t, 4, 2, (mco_objhandle_h)handle);
}

MCO_RET      B_delete                        ( B *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      B_set_allocation_block_size    (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 2, block_size); 
}

MCO_RET      B_set_caching_priority         (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 2, priority); 
}

MCO_RET      B_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 2 ); 
}

MCO_RET      B_checkpoint                    ( B *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      B_ui4_get                       ( B *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      B_ui4_put                       ( B *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      B_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ B *handle )
{ return mco_w_obj_from_cursor( t, c, 2, (mco_objhandle_h)handle ); 
}

MCO_RET      B_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_list_cursor( t, 2, c );
}

MCO_RET      Part_new                           ( mco_trans_h t, /*OUT*/ Part *handle )
{ return mco_w_new_obj_noid( t, 68, 3, (mco_objhandle_h)handle);
}

MCO_RET      Part_delete                        ( Part *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      Part_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 3 ); 
}

MCO_RET      Part_checkpoint                    ( Part *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      Part_pack                          ( Part *handle, /*OUT*/ uint4 * pages_released )
{ return mco_w_compact( (mco_objhandle_h)handle, 3, 3, pages_released); 
}

MCO_RET      Part_type_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 64, 62, 0, dest, dest_size, len); 
}

MCO_RET      Part_type_size                     ( Part *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 64, 62, 0, result); 
}

MCO_RET      Part_type_put                      ( Part *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 64, 62, 0, src, len, 1);
}

MCO_RET      Part_name_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 0, 60, 1, dest, dest_size, len); 
}

MCO_RET      Part_name_size                     ( Part *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 0, 60, 1, result); 
}

MCO_RET      Part_name_put                      ( Part *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 0, 60, 1, src, len, 1);
}

MCO_RET      Part_price_get                     ( Part *handle, /*OUT*/ float * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 4, 40, 2,result);
}

MCO_RET      Part_price_put                     ( Part *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put2( (mco_objhandle_h) handle, 4, 40, 2, 0, u.i); }
}

MCO_RET      Part_code_get                      ( Part *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 8, 44, 3,result);
}

MCO_RET      Part_code_put                      ( Part *handle, uint4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 8, 44, 3, 1, (uint4) value);
}

MCO_RET      Part_dim_read_handle               ( Part *handle, /*OUT*/ Dimensions * h )
{ return mco_w_struct_get2( (mco_objhandle_h)handle, (mco_objhandle_h)h, 12, 48, 4); 
}

MCO_RET      Part_dim_write_handle              ( Part *handle, /*OUT*/ Dimensions * h )
{ return mco_w_struct_put2( (mco_objhandle_h)handle, (mco_objhandle_h)h, 12, 48, 4, 0);
}

MCO_RET      Part_options_at                    ( Part *handle, uint2 index, /*OUT*/ uint4 *result)
{ return mco_w_va_simple_e_get2( (mco_objhandle_h)handle, 24, 0, 5, index, 4, result, 10);
}

MCO_RET      Part_options_get_range             ( Part *handle, uint2 start_index, uint2 num, /*OUT*/ uint4 *dest )
{ return mco_w_va_simple_e_getrange2( (mco_objhandle_h)handle, 24, 0, 5, start_index, 4, num, dest, 10, 0);
}

MCO_RET      Part_options_put                   ( Part *handle, uint2 index, uint4 value )
{ return mco_w_va_simple_e_put2( (mco_objhandle_h)handle, 24, 0, 5, index, 4, 0, &value, 10);
}

MCO_RET      Part_options_put_range             ( Part *handle, uint2 start_index, uint2 num, const uint4 *src )
{ return mco_w_va_simple_e_putrange2( (mco_objhandle_h)handle, 24, 0, 5, start_index, 4, num, 0, src, 10, 0);
}

MCO_RET      Part_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part *handle )
{ return mco_w_obj_from_cursor( t, c, 3, (mco_objhandle_h)handle ); 
}

MCO_RET      Part_ByCode_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 2, c );
}

MCO_RET      Part_ByCode_compare                ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_ByCode_find                   ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_hash_find_scalar(t, 2, a_, (mco_objhandle_h)handle_);
}

MCO_RET      Part_ByType_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 3, c );
}

MCO_RET      Part_ByType_search                 ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part_ByType_compare                ( mco_trans_h t, mco_cursor_h c, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_ByType_pattern_size           ( const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [3];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part_ByType_pattern_search         ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ )
{ mco_external_field_t a_ [3];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part_ByType_pattern_next           ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part_ByType_locate                 ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle)
{ return mco_w_cursor_locate( t, 3, (mco_objhandle_h)handle, c);
}

MCO_RET      Part_IdxCode_index_cursor          ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 4, c );
}

MCO_RET      Part_IdxCode_search                ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 code_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part_IdxCode_compare               ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_IdxCode_pattern_size          ( uint4 code_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part_IdxCode_pattern_search        ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 code_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part_IdxCode_pattern_next          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part_IdxCode_locate                ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle)
{ return mco_w_cursor_locate( t, 4, (mco_objhandle_h)handle, c);
}

MCO_RET      Part_IdxCode_find                  ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_tree_find_scalar(t, 4, a_, (mco_objhandle_h)handle_);
}

MCO_RET      Part2_new                             ( mco_trans_h t, /*OUT*/ Part2 *handle )
{ return mco_w_new_obj_noid( t, 16, 4, (mco_objhandle_h)handle);
}

MCO_RET      Part2_delete                          ( Part2 *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      Part2_delete_all                      ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 4 ); 
}

MCO_RET      Part2_checkpoint                      ( Part2 *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      Part2_broker_id_get                   ( Part2 *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      Part2_broker_id_put                   ( Part2 *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      Part2_password_get                    ( Part2 *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get( (mco_objhandle_h) handle, 8, 1, dest, dest_size, 8);
}

MCO_RET      Part2_password_put                    ( Part2 *handle, const char * src, uint2 len) 
{ return mco_w_chars_put( (mco_objhandle_h)handle, 8, 1, src, len, 8, 0);
}

MCO_RET      Part2_user_id_get                     ( Part2 *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 2, result);
}

MCO_RET      Part2_user_id_put                     ( Part2 *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 4, 2, 1, (uint4) value);
}

MCO_RET      Part2_from_cursor                     ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part2 *handle )
{ return mco_w_obj_from_cursor( t, c, 4, (mco_objhandle_h)handle ); 
}

MCO_RET      Part2_IdxCode_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 5, c );
}

MCO_RET      Part2_IdxCode_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part2_IdxCode_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part2_IdxCode_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part2_IdxCode_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part2_IdxCode_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part2_IdxCode_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part2 * handle)
{ return mco_w_cursor_locate( t, 5, (mco_objhandle_h)handle, c);
}

MCO_RET      Part2_IdxCode_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ Part2 *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_tree_find_scalar(t, 5, a_, (mco_objhandle_h)handle_);
}

MCO_RET      User_new                                 ( mco_trans_h t, /*OUT*/ User *handle )
{ return mco_w_new_obj_noid( t, 16, 5, (mco_objhandle_h)handle);
}

MCO_RET      User_delete                              ( User *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      User_set_allocation_block_size          (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 5, block_size); 
}

MCO_RET      User_set_caching_priority               (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 5, priority); 
}

MCO_RET      User_delete_all                          ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 5 ); 
}

MCO_RET      User_checkpoint                          ( User *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      User_broker_id_get                       ( User *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 0, result);
}

MCO_RET      User_broker_id_put                       ( User *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 4, 0, 0, (uint4) value);
}

MCO_RET      User_user_id_get                         ( User *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 1, result);
}

MCO_RET      User_user_id_put                         ( User *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 1, 1, (uint4) value);
}

MCO_RET      User_password_get                        ( User *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get( (mco_objhandle_h) handle, 8, 2, dest, dest_size, 8);
}

MCO_RET      User_password_put                        ( User *handle, const char * src, uint2 len) 
{ return mco_w_chars_put( (mco_objhandle_h)handle, 8, 2, src, len, 8, 0);
}

MCO_RET      User_from_cursor                         ( mco_trans_h t, mco_cursor_h c, /*OUT*/ User *handle )
{ return mco_w_obj_from_cursor( t, c, 5, (mco_objhandle_h)handle ); 
}

MCO_RET      User_idx_user_id_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 6, c );
}

MCO_RET      User_idx_user_id_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      User_idx_user_id_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      User_idx_user_id_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      User_idx_user_id_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      User_idx_user_id_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      User_idx_user_id_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, User * handle)
{ return mco_w_cursor_locate( t, 6, (mco_objhandle_h)handle, c);
}

MCO_RET      User_idx_user_id_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ User *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_tree_find_scalar(t, 6, a_, (mco_objhandle_h)handle_);
}

MCO_RET      OrderInsert_new                          ( mco_trans_h t, /*OUT*/ OrderInsert *handle )
{ return mco_w_new_obj_noid( t, 59, 6, (mco_objhandle_h)handle);
}

MCO_RET      OrderInsert_delete                       ( OrderInsert *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      OrderInsert_set_allocation_block_size   (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 6, block_size); 
}

MCO_RET      OrderInsert_set_caching_priority        (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 6, priority); 
}

MCO_RET      OrderInsert_delete_all                   ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 6 ); 
}

MCO_RET      OrderInsert_checkpoint                   ( OrderInsert *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      OrderInsert_pack                         ( OrderInsert *handle, /*OUT*/ uint4 * pages_released )
{ return mco_w_compact( (mco_objhandle_h)handle, 6, 6, pages_released); 
}

MCO_RET      OrderInsert_owner_type_get               ( OrderInsert *handle, /*OUT*/ uint2 * result)
{ return mco_w_b2_get2( (mco_objhandle_h) handle, 44, 40, 0,result);
}

MCO_RET      OrderInsert_owner_type_put               ( OrderInsert *handle, uint2 value )
{ return mco_w_b2_put2( (mco_objhandle_h) handle, 44, 40, 0, 0, (uint2) value);
}

MCO_RET      OrderInsert_front_id_get                 ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 8, 32, 1,result);
}

MCO_RET      OrderInsert_front_id_put                 ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 8, 32, 1, 0, (uint4) value);
}

MCO_RET      OrderInsert_session_id_get               ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 20, 2, result);
}

MCO_RET      OrderInsert_session_id_put               ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 20, 2, 0, (uint4) value);
}

MCO_RET      OrderInsert_order_ref_get                ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 36, 3, result);
}

MCO_RET      OrderInsert_order_ref_put                ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 36, 3, 0, (uint4) value);
}

MCO_RET      OrderInsert_user_id_get                  ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 40, 0, 4,result);
}

MCO_RET      OrderInsert_user_id_put                  ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 40, 0, 4, 0, (uint4) value);
}

MCO_RET      OrderInsert_investor_id_get              ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 5, result);
}

MCO_RET      OrderInsert_investor_id_put              ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 4, 5, 0, (uint4) value);
}

MCO_RET      OrderInsert_secu_account_get             ( OrderInsert *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 46, 44, 6, dest, dest_size, 10);
}

MCO_RET      OrderInsert_secu_account_put             ( OrderInsert *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 46, 44, 6, src, len, 10, 0);
}

MCO_RET      OrderInsert_security_code_get            ( OrderInsert *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 32, 42, 7, dest, dest_size, len); 
}

MCO_RET      OrderInsert_security_code_size           ( OrderInsert *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 32, 42, 7, result); 
}

MCO_RET      OrderInsert_security_code_put            ( OrderInsert *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 32, 42, 7, src, len, 0);
}

MCO_RET      OrderInsert_exchange_type_get            ( OrderInsert *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 58, 56, 8,result);
}

MCO_RET      OrderInsert_exchange_type_put            ( OrderInsert *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 58, 56, 8, 0, (uint1) value);
}

MCO_RET      OrderInsert_bs_flag_get                  ( OrderInsert *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 57, 55, 9,result);
}

MCO_RET      OrderInsert_bs_flag_put                  ( OrderInsert *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 57, 55, 9, 0, (uint1) value);
}

MCO_RET      OrderInsert_business_code_get            ( OrderInsert *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 0, 16, 10,result);
}

MCO_RET      OrderInsert_business_code_put            ( OrderInsert *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 0, 16, 10, 0, (uint4) value);
}

MCO_RET      OrderInsert_price_type_get               ( OrderInsert *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 56, 54, 11,result);
}

MCO_RET      OrderInsert_price_type_put               ( OrderInsert *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 56, 54, 11, 0, (uint1) value);
}

MCO_RET      OrderInsert_price_get_chars              ( OrderInsert *handle, char* buf, int buf_size)
{mco_int8 _scaled_num; MCO_RET _rc = OrderInsert_price_get(handle, &_scaled_num); return _rc == MCO_S_OK ? mco_w_numeric_b8_to_string(_scaled_num, 3, buf, buf_size) : _rc; }

MCO_RET      OrderInsert_price_to_chars               (mco_int8 scaled_num, char* buf, int buf_size)
{ return mco_w_numeric_b8_to_string(scaled_num, 3, buf, buf_size); }

MCO_RET      OrderInsert_price_put_chars              ( OrderInsert *handle, char const* buf)
{mco_int8 _scaled_num;  MCO_RET _rc = mco_w_numeric_b8_from_string(&_scaled_num, 3, buf); return _rc == MCO_S_OK ? OrderInsert_price_put(handle, _scaled_num) : _rc; }

MCO_RET      OrderInsert_price_from_chars             ( mco_int8* scaled_num, char const* buf)
{ return mco_w_numeric_b8_from_string(scaled_num, 3, buf); }

MCO_RET      OrderInsert_price_get                    ( OrderInsert *handle, /*OUT*/ mco_int8 * result)
{ return mco_w_b8_get( (mco_objhandle_h) handle, 24, 12, result);
}

MCO_RET      OrderInsert_price_put                    ( OrderInsert *handle, mco_int8 value )
{ return mco_w_b8_put( (mco_objhandle_h) handle, 24, 12, 0, & value);
}

MCO_RET      OrderInsert_volume_get                   ( OrderInsert *handle, /*OUT*/ uint8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 12, 8, 13,result);
}

MCO_RET      OrderInsert_volume_put                   ( OrderInsert *handle, uint8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 12, 8, 13, 0, & value);
}

MCO_RET      OrderInsert_from_cursor                  ( mco_trans_h t, mco_cursor_h c, /*OUT*/ OrderInsert *handle )
{ return mco_w_obj_from_cursor( t, c, 6, (mco_objhandle_h)handle ); 
}

MCO_RET      Order_new                              ( mco_trans_h t, /*OUT*/ Order *handle )
{ return mco_w_new_obj_noid( t, 104, 7, (mco_objhandle_h)handle);
}

MCO_RET      Order_delete                           ( Order *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      Order_set_allocation_block_size       (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 7, block_size); 
}

MCO_RET      Order_set_caching_priority            (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 7, priority); 
}

MCO_RET      Order_delete_all                       ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 7 ); 
}

MCO_RET      Order_checkpoint                       ( Order *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      Order_pack                             ( Order *handle, /*OUT*/ uint4 * pages_released )
{ return mco_w_compact( (mco_objhandle_h)handle, 7, 7, pages_released); 
}

MCO_RET      Order_owner_type_get                   ( Order *handle, /*OUT*/ uint2 * result)
{ return mco_w_b2_get2( (mco_objhandle_h) handle, 68, 64, 0,result);
}

MCO_RET      Order_owner_type_put                   ( Order *handle, uint2 value )
{ return mco_w_b2_put2( (mco_objhandle_h) handle, 68, 64, 0, 0, (uint2) value);
}

MCO_RET      Order_front_id_get                     ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 8, 40, 1,result);
}

MCO_RET      Order_front_id_put                     ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 8, 40, 1, 0, (uint4) value);
}

MCO_RET      Order_session_id_get                   ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 20, 24, 2,result);
}

MCO_RET      Order_session_id_put                   ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 20, 24, 2, 0, (uint4) value);
}

MCO_RET      Order_order_ref_get                    ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 28, 3, result);
}

MCO_RET      Order_order_ref_put                    ( Order *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 28, 3, 0, (uint4) value);
}

MCO_RET      Order_user_id_get                      ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 40, 44, 4,result);
}

MCO_RET      Order_user_id_put                      ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 40, 44, 4, 0, (uint4) value);
}

MCO_RET      Order_investor_id_get                  ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 48, 52, 5,result);
}

MCO_RET      Order_investor_id_put                  ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 48, 52, 5, 0, (uint4) value);
}

MCO_RET      Order_secu_account_get                 ( Order *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 70, 68, 6, dest, dest_size, 10);
}

MCO_RET      Order_secu_account_put                 ( Order *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 70, 68, 6, src, len, 10, 0);
}

MCO_RET      Order_security_code_get                ( Order *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 24, 66, 7, dest, dest_size, len); 
}

MCO_RET      Order_security_code_size               ( Order *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 24, 66, 7, result); 
}

MCO_RET      Order_security_code_put                ( Order *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 24, 66, 7, src, len, 0);
}

MCO_RET      Order_exchange_type_get                ( Order *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 93, 91, 8,result);
}

MCO_RET      Order_exchange_type_put                ( Order *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 93, 91, 8, 0, (uint1) value);
}

MCO_RET      Order_bs_flag_get                      ( Order *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 81, 79, 9,result);
}

MCO_RET      Order_bs_flag_put                      ( Order *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 81, 79, 9, 0, (uint1) value);
}

MCO_RET      Order_business_code_get                ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 44, 48, 10,result);
}

MCO_RET      Order_business_code_put                ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 44, 48, 10, 0, (uint4) value);
}

MCO_RET      Order_price_type_get                   ( Order *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 80, 78, 11,result);
}

MCO_RET      Order_price_type_put                   ( Order *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 80, 78, 11, 0, (uint1) value);
}

MCO_RET      Order_price_get_chars                  ( Order *handle, char* buf, int buf_size)
{mco_int8 _scaled_num; MCO_RET _rc = Order_price_get(handle, &_scaled_num); return _rc == MCO_S_OK ? mco_w_numeric_b8_to_string(_scaled_num, 3, buf, buf_size) : _rc; }

MCO_RET      Order_price_to_chars                   (mco_int8 scaled_num, char* buf, int buf_size)
{ return mco_w_numeric_b8_to_string(scaled_num, 3, buf, buf_size); }

MCO_RET      Order_price_put_chars                  ( Order *handle, char const* buf)
{mco_int8 _scaled_num;  MCO_RET _rc = mco_w_numeric_b8_from_string(&_scaled_num, 3, buf); return _rc == MCO_S_OK ? Order_price_put(handle, _scaled_num) : _rc; }

MCO_RET      Order_price_from_chars                 ( mco_int8* scaled_num, char const* buf)
{ return mco_w_numeric_b8_from_string(scaled_num, 3, buf); }

MCO_RET      Order_price_get                        ( Order *handle, /*OUT*/ mco_int8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 52, 56, 12,result);
}

MCO_RET      Order_price_put                        ( Order *handle, mco_int8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 52, 56, 12, 0, & value);
}

MCO_RET      Order_volume_get                       ( Order *handle, /*OUT*/ uint8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 60, 0, 13,result);
}

MCO_RET      Order_volume_put                       ( Order *handle, uint8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 60, 0, 13, 0, & value);
}

MCO_RET      Order_branch_id_get                    ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 0, 12, 14,result);
}

MCO_RET      Order_branch_id_put                    ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 0, 12, 14, 0, (uint4) value);
}

MCO_RET      Order_pbu_id_get                       ( Order *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 4, 8, 15,result);
}

MCO_RET      Order_pbu_id_put                       ( Order *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 4, 8, 15, 0, (uint4) value);
}

MCO_RET      Order_order_sys_id_get                 ( Order *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 94, 92, 16, dest, dest_size, 10);
}

MCO_RET      Order_order_sys_id_put                 ( Order *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 94, 92, 16, src, len, 10, 0);
}

MCO_RET      Order_order_exchange_id_get            ( Order *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 83, 81, 17, dest, dest_size, 10);
}

MCO_RET      Order_order_exchange_id_put            ( Order *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 83, 81, 17, src, len, 10, 0);
}

MCO_RET      Order_status_get                       ( Order *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 82, 80, 18,result);
}

MCO_RET      Order_status_put                       ( Order *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 82, 80, 18, 0, (uint1) value);
}

MCO_RET      Order_volume_traded_get                ( Order *handle, /*OUT*/ uint8 * result)
{ return mco_w_b8_get( (mco_objhandle_h) handle, 32, 19, result);
}

MCO_RET      Order_volume_traded_put                ( Order *handle, uint8 value )
{ return mco_w_b8_put( (mco_objhandle_h) handle, 32, 19, 0, & value);
}

MCO_RET      Order_amount_traded_get_chars          ( Order *handle, char* buf, int buf_size)
{mco_int8 _scaled_num; MCO_RET _rc = Order_amount_traded_get(handle, &_scaled_num); return _rc == MCO_S_OK ? mco_w_numeric_b8_to_string(_scaled_num, 2, buf, buf_size) : _rc; }

MCO_RET      Order_amount_traded_to_chars           (mco_int8 scaled_num, char* buf, int buf_size)
{ return mco_w_numeric_b8_to_string(scaled_num, 2, buf, buf_size); }

MCO_RET      Order_amount_traded_put_chars          ( Order *handle, char const* buf)
{mco_int8 _scaled_num;  MCO_RET _rc = mco_w_numeric_b8_from_string(&_scaled_num, 2, buf); return _rc == MCO_S_OK ? Order_amount_traded_put(handle, _scaled_num) : _rc; }

MCO_RET      Order_amount_traded_from_chars         ( mco_int8* scaled_num, char const* buf)
{ return mco_w_numeric_b8_from_string(scaled_num, 2, buf); }

MCO_RET      Order_amount_traded_get                ( Order *handle, /*OUT*/ mco_int8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 12, 16, 20,result);
}

MCO_RET      Order_amount_traded_put                ( Order *handle, mco_int8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 12, 16, 20, 0, & value);
}

MCO_RET      Order_from_cursor                      ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Order *handle )
{ return mco_w_obj_from_cursor( t, c, 7, (mco_objhandle_h)handle ); 
}

MCO_RET      OrderAction_new                              ( mco_trans_h t, /*OUT*/ OrderAction *handle )
{ return mco_w_new_obj_noid( t, 74, 8, (mco_objhandle_h)handle);
}

MCO_RET      OrderAction_delete                           ( OrderAction *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      OrderAction_set_allocation_block_size       (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 8, block_size); 
}

MCO_RET      OrderAction_set_caching_priority            (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 8, priority); 
}

MCO_RET      OrderAction_delete_all                       ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 8 ); 
}

MCO_RET      OrderAction_checkpoint                       ( OrderAction *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      OrderAction_pack                             ( OrderAction *handle, /*OUT*/ uint4 * pages_released )
{ return mco_w_compact( (mco_objhandle_h)handle, 8, 8, pages_released); 
}

MCO_RET      OrderAction_owner_type_get                   ( OrderAction *handle, /*OUT*/ uint2 * result)
{ return mco_w_b2_get2( (mco_objhandle_h) handle, 40, 38, 0,result);
}

MCO_RET      OrderAction_owner_type_put                   ( OrderAction *handle, uint2 value )
{ return mco_w_b2_put2( (mco_objhandle_h) handle, 40, 38, 0, 0, (uint2) value);
}

MCO_RET      OrderAction_user_id_get                      ( OrderAction *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 36, 0, 1,result);
}

MCO_RET      OrderAction_user_id_put                      ( OrderAction *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 36, 0, 1, 0, (uint4) value);
}

MCO_RET      OrderAction_investor_id_get                  ( OrderAction *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 24, 2, result);
}

MCO_RET      OrderAction_investor_id_put                  ( OrderAction *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 24, 2, 0, (uint4) value);
}

MCO_RET      OrderAction_front_id_get                     ( OrderAction *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 32, 3, result);
}

MCO_RET      OrderAction_front_id_put                     ( OrderAction *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 32, 3, 0, (uint4) value);
}

MCO_RET      OrderAction_session_id_get                   ( OrderAction *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 0, 20, 4,result);
}

MCO_RET      OrderAction_session_id_put                   ( OrderAction *handle, int4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 0, 20, 4, 0, (uint4) value);
}

MCO_RET      OrderAction_order_ref_get                    ( OrderAction *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 28, 5, result);
}

MCO_RET      OrderAction_order_ref_put                    ( OrderAction *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 28, 5, 0, (uint4) value);
}

MCO_RET      OrderAction_order_sys_id_get                 ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 42, 40, 6, dest, dest_size, 10);
}

MCO_RET      OrderAction_order_sys_id_put                 ( OrderAction *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 42, 40, 6, src, len, 10, 0);
}

MCO_RET      OrderAction_exchange_type_get                ( OrderAction *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 73, 71, 7,result);
}

MCO_RET      OrderAction_exchange_type_put                ( OrderAction *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 73, 71, 7, 0, (uint1) value);
}

MCO_RET      OrderAction_order_exchange_id_get            ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 63, 61, 8, dest, dest_size, 10);
}

MCO_RET      OrderAction_order_exchange_id_put            ( OrderAction *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 63, 61, 8, src, len, 10, 0);
}

MCO_RET      OrderAction_secu_account_get                 ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get2( (mco_objhandle_h) handle, 53, 51, 9, dest, dest_size, 10);
}

MCO_RET      OrderAction_secu_account_put                 ( OrderAction *handle, const char * src, uint2 len) 
{ return mco_w_chars_put2( (mco_objhandle_h)handle, 53, 51, 9, src, len, 10, 0);
}

MCO_RET      OrderAction_security_code_get                ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 4, 36, 10, dest, dest_size, len); 
}

MCO_RET      OrderAction_security_code_size               ( OrderAction *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 4, 36, 10, result); 
}

MCO_RET      OrderAction_security_code_put                ( OrderAction *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 4, 36, 10, src, len, 0);
}

MCO_RET      OrderAction_bs_flag_get                      ( OrderAction *handle, /*OUT*/ uint1 * result)
{ return mco_w_b1_get2( (mco_objhandle_h) handle, 52, 50, 11,result);
}

MCO_RET      OrderAction_bs_flag_put                      ( OrderAction *handle, uint1 value )
{ return mco_w_b1_put2( (mco_objhandle_h) handle, 52, 50, 11, 0, (uint1) value);
}

MCO_RET      OrderAction_volume_get                       ( OrderAction *handle, /*OUT*/ uint8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 8, 12, 12,result);
}

MCO_RET      OrderAction_volume_put                       ( OrderAction *handle, uint8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 8, 12, 12, 0, & value);
}

MCO_RET      OrderAction_price_get_chars                  ( OrderAction *handle, char* buf, int buf_size)
{mco_int8 _scaled_num; MCO_RET _rc = OrderAction_price_get(handle, &_scaled_num); return _rc == MCO_S_OK ? mco_w_numeric_b8_to_string(_scaled_num, 3, buf, buf_size) : _rc; }

MCO_RET      OrderAction_price_to_chars                   (mco_int8 scaled_num, char* buf, int buf_size)
{ return mco_w_numeric_b8_to_string(scaled_num, 3, buf, buf_size); }

MCO_RET      OrderAction_price_put_chars                  ( OrderAction *handle, char const* buf)
{mco_int8 _scaled_num;  MCO_RET _rc = mco_w_numeric_b8_from_string(&_scaled_num, 3, buf); return _rc == MCO_S_OK ? OrderAction_price_put(handle, _scaled_num) : _rc; }

MCO_RET      OrderAction_price_from_chars                 ( mco_int8* scaled_num, char const* buf)
{ return mco_w_numeric_b8_from_string(scaled_num, 3, buf); }

MCO_RET      OrderAction_price_get                        ( OrderAction *handle, /*OUT*/ mco_int8 * result)
{ return mco_w_b8_get2( (mco_objhandle_h) handle, 16, 4, 13,result);
}

MCO_RET      OrderAction_price_put                        ( OrderAction *handle, mco_int8 value )
{ return mco_w_b8_put2( (mco_objhandle_h) handle, 16, 4, 13, 0, & value);
}

MCO_RET      OrderAction_from_cursor                      ( mco_trans_h t, mco_cursor_h c, /*OUT*/ OrderAction *handle )
{ return mco_w_obj_from_cursor( t, c, 8, (mco_objhandle_h)handle ); 
}

MCO_RET      Dimensions_width_get             ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 8, 0, result);
}

MCO_RET      Dimensions_width_put             ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 8, 0, 0, u.i); }
}

MCO_RET      Dimensions_length_get            ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      Dimensions_length_put            ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, u.i); }
}

MCO_RET      Dimensions_height_get            ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 0, result);
}

MCO_RET      Dimensions_height_put            ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 4, 0, 0, u.i); }
}

MCO_RET      Dimensions_fixed_get             ( Dimensions *handle_, Dimensions_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = Dimensions_width_get(handle_, &dst_->width)) == MCO_S_OK &&
    (rc_ = Dimensions_length_get(handle_, &dst_->length)) == MCO_S_OK &&
    (rc_ = Dimensions_height_get(handle_, &dst_->height)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Dimensions_fixed_put             ( Dimensions *handle_, Dimensions_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = Dimensions_width_put(handle_, src_->width)) == MCO_S_OK &&
    (rc_ = Dimensions_length_put(handle_, src_->length)) == MCO_S_OK &&
    (rc_ = Dimensions_height_put(handle_, src_->height)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      A_fixed_get                     ( A *handle_, A_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = A_ui4_get(handle_, &dst_->ui4)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      A_fixed_put                     ( A *handle_, A_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = A_ui4_put(handle_, src_->ui4)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      B_fixed_get                     ( B *handle_, B_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = B_ui4_get(handle_, &dst_->ui4)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      B_fixed_put                     ( B *handle_, B_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = B_ui4_put(handle_, src_->ui4)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      Part_fixed_get                     ( Part *handle_, Part_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  Dimensions dim;
  return
    (rc_ = Part_price_get(handle_, &dst_->price)) == MCO_S_OK &&
    (rc_ = Part_code_get(handle_, &dst_->code)) == MCO_S_OK &&
    (rc_ = Part_dim_read_handle(handle_, &dim)) == MCO_S_OK && ((rc_ = Dimensions_fixed_get(&dim, &dst_->dim)) == MCO_S_OK || (has_nulls_ = rc_) == MCO_S_NULL_VALUE) &&
    (rc_ = Part_options_get_range(handle_, 0, 10, dst_->options)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Part_fixed_put                     ( Part *handle_, Part_fixed const* src_ )
{ MCO_RET rc_;
  Dimensions dim;
  return
    (rc_ = Part_price_put(handle_, src_->price)) == MCO_S_OK &&
    (rc_ = Part_code_put(handle_, src_->code)) == MCO_S_OK &&
    (rc_ = Part_dim_write_handle(handle_, &dim)) == MCO_S_OK && (rc_ = Dimensions_fixed_put(&dim, &src_->dim)) == MCO_S_OK &&
    (rc_ = Part_options_put_range(handle_, 0, 10, src_->options)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      Part2_fixed_get                       ( Part2 *handle_, Part2_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = Part2_broker_id_get(handle_, &dst_->broker_id)) == MCO_S_OK &&
    (rc_ = Part2_password_get(handle_, dst_->password, 8)) == MCO_S_OK &&
    (rc_ = Part2_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Part2_fixed_put                       ( Part2 *handle_, Part2_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = Part2_broker_id_put(handle_, src_->broker_id)) == MCO_S_OK &&
    (rc_ = Part2_password_put(handle_, src_->password, 8)) == MCO_S_OK &&
    (rc_ = Part2_user_id_put(handle_, src_->user_id)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      User_fixed_get                           ( User *handle_, User_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = User_broker_id_get(handle_, &dst_->broker_id)) == MCO_S_OK &&
    (rc_ = User_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK &&
    (rc_ = User_password_get(handle_, dst_->password, 8)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      User_fixed_put                           ( User *handle_, User_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = User_broker_id_put(handle_, src_->broker_id)) == MCO_S_OK &&
    (rc_ = User_user_id_put(handle_, src_->user_id)) == MCO_S_OK &&
    (rc_ = User_password_put(handle_, src_->password, 8)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      OrderInsert_fixed_get                    ( OrderInsert *handle_, OrderInsert_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = OrderInsert_owner_type_get(handle_, &dst_->owner_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_front_id_get(handle_, &dst_->front_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_session_id_get(handle_, &dst_->session_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_order_ref_get(handle_, &dst_->order_ref)) == MCO_S_OK &&
    (rc_ = OrderInsert_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_investor_id_get(handle_, &dst_->investor_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_secu_account_get(handle_, dst_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = OrderInsert_exchange_type_get(handle_, &dst_->exchange_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_bs_flag_get(handle_, &dst_->bs_flag)) == MCO_S_OK &&
    (rc_ = OrderInsert_business_code_get(handle_, &dst_->business_code)) == MCO_S_OK &&
    (rc_ = OrderInsert_price_type_get(handle_, &dst_->price_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_price_get(handle_, &dst_->price)) == MCO_S_OK &&
    (rc_ = OrderInsert_volume_get(handle_, &dst_->volume)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      OrderInsert_fixed_put                    ( OrderInsert *handle_, OrderInsert_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = OrderInsert_owner_type_put(handle_, src_->owner_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_front_id_put(handle_, src_->front_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_session_id_put(handle_, src_->session_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_order_ref_put(handle_, src_->order_ref)) == MCO_S_OK &&
    (rc_ = OrderInsert_user_id_put(handle_, src_->user_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_investor_id_put(handle_, src_->investor_id)) == MCO_S_OK &&
    (rc_ = OrderInsert_secu_account_put(handle_, src_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = OrderInsert_exchange_type_put(handle_, src_->exchange_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_bs_flag_put(handle_, src_->bs_flag)) == MCO_S_OK &&
    (rc_ = OrderInsert_business_code_put(handle_, src_->business_code)) == MCO_S_OK &&
    (rc_ = OrderInsert_price_type_put(handle_, src_->price_type)) == MCO_S_OK &&
    (rc_ = OrderInsert_price_put(handle_, src_->price)) == MCO_S_OK &&
    (rc_ = OrderInsert_volume_put(handle_, src_->volume)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      Order_fixed_get                        ( Order *handle_, Order_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = Order_owner_type_get(handle_, &dst_->owner_type)) == MCO_S_OK &&
    (rc_ = Order_front_id_get(handle_, &dst_->front_id)) == MCO_S_OK &&
    (rc_ = Order_session_id_get(handle_, &dst_->session_id)) == MCO_S_OK &&
    (rc_ = Order_order_ref_get(handle_, &dst_->order_ref)) == MCO_S_OK &&
    (rc_ = Order_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK &&
    (rc_ = Order_investor_id_get(handle_, &dst_->investor_id)) == MCO_S_OK &&
    (rc_ = Order_secu_account_get(handle_, dst_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = Order_exchange_type_get(handle_, &dst_->exchange_type)) == MCO_S_OK &&
    (rc_ = Order_bs_flag_get(handle_, &dst_->bs_flag)) == MCO_S_OK &&
    (rc_ = Order_business_code_get(handle_, &dst_->business_code)) == MCO_S_OK &&
    (rc_ = Order_price_type_get(handle_, &dst_->price_type)) == MCO_S_OK &&
    (rc_ = Order_price_get(handle_, &dst_->price)) == MCO_S_OK &&
    (rc_ = Order_volume_get(handle_, &dst_->volume)) == MCO_S_OK &&
    (rc_ = Order_branch_id_get(handle_, &dst_->branch_id)) == MCO_S_OK &&
    (rc_ = Order_pbu_id_get(handle_, &dst_->pbu_id)) == MCO_S_OK &&
    (rc_ = Order_order_sys_id_get(handle_, dst_->order_sys_id, 10)) == MCO_S_OK &&
    (rc_ = Order_order_exchange_id_get(handle_, dst_->order_exchange_id, 10)) == MCO_S_OK &&
    (rc_ = Order_status_get(handle_, &dst_->status)) == MCO_S_OK &&
    (rc_ = Order_volume_traded_get(handle_, &dst_->volume_traded)) == MCO_S_OK &&
    (rc_ = Order_amount_traded_get(handle_, &dst_->amount_traded)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Order_fixed_put                        ( Order *handle_, Order_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = Order_owner_type_put(handle_, src_->owner_type)) == MCO_S_OK &&
    (rc_ = Order_front_id_put(handle_, src_->front_id)) == MCO_S_OK &&
    (rc_ = Order_session_id_put(handle_, src_->session_id)) == MCO_S_OK &&
    (rc_ = Order_order_ref_put(handle_, src_->order_ref)) == MCO_S_OK &&
    (rc_ = Order_user_id_put(handle_, src_->user_id)) == MCO_S_OK &&
    (rc_ = Order_investor_id_put(handle_, src_->investor_id)) == MCO_S_OK &&
    (rc_ = Order_secu_account_put(handle_, src_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = Order_exchange_type_put(handle_, src_->exchange_type)) == MCO_S_OK &&
    (rc_ = Order_bs_flag_put(handle_, src_->bs_flag)) == MCO_S_OK &&
    (rc_ = Order_business_code_put(handle_, src_->business_code)) == MCO_S_OK &&
    (rc_ = Order_price_type_put(handle_, src_->price_type)) == MCO_S_OK &&
    (rc_ = Order_price_put(handle_, src_->price)) == MCO_S_OK &&
    (rc_ = Order_volume_put(handle_, src_->volume)) == MCO_S_OK &&
    (rc_ = Order_branch_id_put(handle_, src_->branch_id)) == MCO_S_OK &&
    (rc_ = Order_pbu_id_put(handle_, src_->pbu_id)) == MCO_S_OK &&
    (rc_ = Order_order_sys_id_put(handle_, src_->order_sys_id, 10)) == MCO_S_OK &&
    (rc_ = Order_order_exchange_id_put(handle_, src_->order_exchange_id, 10)) == MCO_S_OK &&
    (rc_ = Order_status_put(handle_, src_->status)) == MCO_S_OK &&
    (rc_ = Order_volume_traded_put(handle_, src_->volume_traded)) == MCO_S_OK &&
    (rc_ = Order_amount_traded_put(handle_, src_->amount_traded)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      OrderAction_fixed_get                        ( OrderAction *handle_, OrderAction_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = OrderAction_owner_type_get(handle_, &dst_->owner_type)) == MCO_S_OK &&
    (rc_ = OrderAction_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK &&
    (rc_ = OrderAction_investor_id_get(handle_, &dst_->investor_id)) == MCO_S_OK &&
    (rc_ = OrderAction_front_id_get(handle_, &dst_->front_id)) == MCO_S_OK &&
    (rc_ = OrderAction_session_id_get(handle_, &dst_->session_id)) == MCO_S_OK &&
    (rc_ = OrderAction_order_ref_get(handle_, &dst_->order_ref)) == MCO_S_OK &&
    (rc_ = OrderAction_order_sys_id_get(handle_, dst_->order_sys_id, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_exchange_type_get(handle_, &dst_->exchange_type)) == MCO_S_OK &&
    (rc_ = OrderAction_order_exchange_id_get(handle_, dst_->order_exchange_id, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_secu_account_get(handle_, dst_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_bs_flag_get(handle_, &dst_->bs_flag)) == MCO_S_OK &&
    (rc_ = OrderAction_volume_get(handle_, &dst_->volume)) == MCO_S_OK &&
    (rc_ = OrderAction_price_get(handle_, &dst_->price)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      OrderAction_fixed_put                        ( OrderAction *handle_, OrderAction_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = OrderAction_owner_type_put(handle_, src_->owner_type)) == MCO_S_OK &&
    (rc_ = OrderAction_user_id_put(handle_, src_->user_id)) == MCO_S_OK &&
    (rc_ = OrderAction_investor_id_put(handle_, src_->investor_id)) == MCO_S_OK &&
    (rc_ = OrderAction_front_id_put(handle_, src_->front_id)) == MCO_S_OK &&
    (rc_ = OrderAction_session_id_put(handle_, src_->session_id)) == MCO_S_OK &&
    (rc_ = OrderAction_order_ref_put(handle_, src_->order_ref)) == MCO_S_OK &&
    (rc_ = OrderAction_order_sys_id_put(handle_, src_->order_sys_id, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_exchange_type_put(handle_, src_->exchange_type)) == MCO_S_OK &&
    (rc_ = OrderAction_order_exchange_id_put(handle_, src_->order_exchange_id, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_secu_account_put(handle_, src_->secu_account, 10)) == MCO_S_OK &&
    (rc_ = OrderAction_bs_flag_put(handle_, src_->bs_flag)) == MCO_S_OK &&
    (rc_ = OrderAction_volume_put(handle_, src_->volume)) == MCO_S_OK &&
    (rc_ = OrderAction_price_put(handle_, src_->price)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

