/* Generated by eXtremeDB Schema Compiler, build 1797, rev. stable, rev. 23320
 * at Wed Jan  2 19:26:16 2019
 */

#if defined(MCO_CPP_INTERFACE) && defined(__MCO__genericdb__H__)
#error C API schema file genericdb.h should not be included directly from C++ application
#endif
#ifndef __MCO__genericdb__H__
#define __MCO__genericdb__H__

#ifdef __cplusplus
extern "C" { 
#endif

#include "mco.h"
#include "mcouda.h"

#ifndef MCO_COMP_VER_MAJOR 
#define MCO_COMP_VER_MAJOR 8
#define MCO_COMP_VER_MINOR 0
#define MCO_COMP_BUILD_NUM 1797
#define MCO_COMP_REVISION "stable, rev. 23320"
#endif /*MCO_COMP_VER_MAJOR*/ 

#if !defined(MCO_MEMCPY_DEFINED) && !MCO_CFG_BUILTIN_MEMCPY
#define MCO_MEMCPY_DEFINED
void mco_memcpy(void* dest, const void* src, mco_size_t nbt);
#endif /*MCO_MEMCPY_DEFINED*/





/*---------------------------------------------------------------------*/
/* Dictionary                                                          */

mco_dictionary_h genericdb_get_dictionary(void);

mco_calculator_h genericdb_get_calculator(void);

#ifdef MCO_CPP_INTERFACE
namespace genericdb
{
#endif


/*---------------------------------------------------------------------*/
/* Handles and Class Codes                                             */

#ifndef MCO_CPP_INTERFACE
typedef struct A_          { MCO_Hf h; }  A;
#else
class A;
#endif
#define                                   A_code           1
#ifndef MCO_CPP_INTERFACE
typedef struct B_          { MCO_Hf h; }  B;
#else
class B;
#endif
#define                                   B_code           2
#ifndef MCO_CPP_INTERFACE
typedef struct Part_       { MCO_Hf h; }  Part;
#else
class Part;
#endif
#define                                   Part_code        3
#ifndef MCO_CPP_INTERFACE
typedef struct Part2_      { MCO_Hf h; }  Part2;
#else
class Part2;
#endif
#define                                   Part2_code       4
#ifndef MCO_CPP_INTERFACE
typedef struct User_       { MCO_Hf h; }  User;
#else
class User;
#endif
#define                                   User_code        5
#ifndef MCO_CPP_INTERFACE
typedef struct OrderInsert_{ MCO_Hf h; }  OrderInsert;
#else
class OrderInsert;
#endif
#define                                   OrderInsert_code 6
#ifndef MCO_CPP_INTERFACE
typedef struct Order_      { MCO_Hf h; }  Order;
#else
class Order;
#endif
#define                                   Order_code       7
#ifndef MCO_CPP_INTERFACE
typedef struct OrderAction_{ MCO_Hf h; }  OrderAction;
#else
class OrderAction;
#endif
#define                                   OrderAction_code 8
#ifndef MCO_CPP_INTERFACE
typedef struct Dimensions_ { MCO_Hf h; }  Dimensions;
#else
struct Dimensions;
#endif


/*---------------------------------------------------------------------*/
/* Structures for fixed part of the structure                          */

typedef struct Dimensions_fixed_ {
  float width;
  float length;
  float height;
} Dimensions_fixed;

typedef struct A_fixed_ {
  uint4 ui4;
} A_fixed;

typedef struct B_fixed_ {
  uint4 ui4;
} B_fixed;

typedef struct Part_fixed_ {
  float price;
  uint4 code;
  Dimensions_fixed dim;
  uint4 options[10];
} Part_fixed;

typedef struct Part2_fixed_ {
  int4 broker_id;
  char password[8];
  uint4 user_id;
} Part2_fixed;

typedef struct User_fixed_ {
  int4 broker_id;
  uint4 user_id;
  char password[8];
} User_fixed;

typedef struct OrderInsert_fixed_ {
  uint2 owner_type;
  int4 front_id;
  int4 session_id;
  int4 order_ref;
  int4 user_id;
  int4 investor_id;
  char secu_account[10];
  uint1 exchange_type;
  uint1 bs_flag;
  int4 business_code;
  uint1 price_type;
  mco_int8 price;
  uint8 volume;
} OrderInsert_fixed;

typedef struct Order_fixed_ {
  uint2 owner_type;
  int4 front_id;
  int4 session_id;
  int4 order_ref;
  int4 user_id;
  int4 investor_id;
  char secu_account[10];
  uint1 exchange_type;
  uint1 bs_flag;
  int4 business_code;
  uint1 price_type;
  mco_int8 price;
  uint8 volume;
  int4 branch_id;
  int4 pbu_id;
  char order_sys_id[10];
  char order_exchange_id[10];
  uint1 status;
  uint8 volume_traded;
  mco_int8 amount_traded;
} Order_fixed;

typedef struct OrderAction_fixed_ {
  uint2 owner_type;
  int4 user_id;
  int4 investor_id;
  int4 front_id;
  int4 session_id;
  int4 order_ref;
  char order_sys_id[10];
  uint1 exchange_type;
  char order_exchange_id[10];
  char secu_account[10];
  uint1 bs_flag;
  uint8 volume;
  mco_int8 price;
} OrderAction_fixed;



/*---------------------------------------------------------------------*/
/* class A methods                                                     */

MCO_RET      A_new                           ( mco_trans_h t, /*OUT*/ A *handle );
MCO_RET      A_delete                        ( A *handle );
MCO_RET      A_delete_all                    ( mco_trans_h t );
MCO_RET      A_checkpoint                    ( A *handle );

MCO_RET      A_ui4_get                       ( A *handle, /*OUT*/ uint4 * result);
MCO_RET      A_ui4_put                       ( A *handle, uint4 value );

MCO_RET      A_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ A *handle );
MCO_RET      A_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c );

/*---------------------------------------------------------------------*/
/* class B methods                                                     */

MCO_RET      B_new                           ( mco_trans_h t, /*OUT*/ B *handle );
MCO_RET      B_delete                        ( B *handle );
MCO_RET      B_set_allocation_block_size    (mco_trans_h t, mco_size_t block_size);
MCO_RET      B_set_caching_priority         (mco_trans_h t, int priority);
MCO_RET      B_delete_all                    ( mco_trans_h t );
MCO_RET      B_checkpoint                    ( B *handle );

MCO_RET      B_ui4_get                       ( B *handle, /*OUT*/ uint4 * result);
MCO_RET      B_ui4_put                       ( B *handle, uint4 value );

MCO_RET      B_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ B *handle );
MCO_RET      B_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c );

/*---------------------------------------------------------------------*/
/* class Part methods                                                  */

MCO_RET      Part_new                           ( mco_trans_h t, /*OUT*/ Part *handle );
MCO_RET      Part_delete                        ( Part *handle );
MCO_RET      Part_delete_all                    ( mco_trans_h t );
MCO_RET      Part_checkpoint                    ( Part *handle );
MCO_RET      Part_pack                          ( Part *handle, /*OUT*/ uint4 * pages_released );

MCO_RET      Part_type_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len);
MCO_RET      Part_type_size                     ( Part *handle, /*OUT*/ uint2 *result);
MCO_RET      Part_type_put                      ( Part *handle, const char * src, uint2 len);

MCO_RET      Part_name_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len);
MCO_RET      Part_name_size                     ( Part *handle, /*OUT*/ uint2 *result);
MCO_RET      Part_name_put                      ( Part *handle, const char * src, uint2 len);

MCO_RET      Part_price_get                     ( Part *handle, /*OUT*/ float * result);
MCO_RET      Part_price_put                     ( Part *handle, float value );

MCO_RET      Part_code_get                      ( Part *handle, /*OUT*/ uint4 * result);
MCO_RET      Part_code_put                      ( Part *handle, uint4 value );

MCO_RET      Part_dim_read_handle               ( Part *handle, /*OUT*/ Dimensions * h );
MCO_RET      Part_dim_write_handle              ( Part *handle, /*OUT*/ Dimensions * h );

#define Part_options_length 10
MCO_RET      Part_options_at                    ( Part *handle, uint2 index, /*OUT*/ uint4 *result);
MCO_RET      Part_options_get_range             ( Part *handle, uint2 start_index, uint2 num, /*OUT*/ uint4 *dest );
MCO_RET      Part_options_put                   ( Part *handle, uint2 index, uint4 value );
MCO_RET      Part_options_put_range             ( Part *handle, uint2 start_index, uint2 num, const uint4 *src );

MCO_RET      Part_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part *handle );

MCO_RET      Part_ByCode_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c );
MCO_RET      Part_ByCode_compare                ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ );
MCO_RET      Part_ByCode_find                   ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_);

MCO_RET      Part_ByType_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c );
MCO_RET      Part_ByType_search                 ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ );
MCO_RET      Part_ByType_compare                ( mco_trans_h t, mco_cursor_h c, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ int *result_ );
MCO_RET      Part_ByType_pattern_size           ( const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ uint4 *size_);
MCO_RET      Part_ByType_pattern_search         ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ );
MCO_RET      Part_ByType_pattern_next           ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern );
MCO_RET      Part_ByType_locate                 ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle);

MCO_RET      Part_IdxCode_index_cursor          ( mco_trans_h t, /*OUT*/ mco_cursor_h c );
MCO_RET      Part_IdxCode_search                ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 code_key_ );
MCO_RET      Part_IdxCode_compare               ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ );
MCO_RET      Part_IdxCode_pattern_size          ( uint4 code_key_, /*OUT*/ uint4 *size_);
MCO_RET      Part_IdxCode_pattern_search        ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 code_key_ );
MCO_RET      Part_IdxCode_pattern_next          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern );
MCO_RET      Part_IdxCode_locate                ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle);
MCO_RET      Part_IdxCode_find                  ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_);

/*---------------------------------------------------------------------*/
/* class Part2 methods                                                 */

MCO_RET      Part2_new                             ( mco_trans_h t, /*OUT*/ Part2 *handle );
MCO_RET      Part2_delete                          ( Part2 *handle );
MCO_RET      Part2_delete_all                      ( mco_trans_h t );
MCO_RET      Part2_checkpoint                      ( Part2 *handle );

MCO_RET      Part2_broker_id_get                   ( Part2 *handle, /*OUT*/ int4 * result);
MCO_RET      Part2_broker_id_put                   ( Part2 *handle, int4 value );

MCO_RET      Part2_password_get                    ( Part2 *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      Part2_password_put                    ( Part2 *handle, const char * src, uint2 len) ;

MCO_RET      Part2_user_id_get                     ( Part2 *handle, /*OUT*/ uint4 * result);
MCO_RET      Part2_user_id_put                     ( Part2 *handle, uint4 value );

MCO_RET      Part2_from_cursor                     ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part2 *handle );

MCO_RET      Part2_IdxCode_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c );
MCO_RET      Part2_IdxCode_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ );
MCO_RET      Part2_IdxCode_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ );
MCO_RET      Part2_IdxCode_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_);
MCO_RET      Part2_IdxCode_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ );
MCO_RET      Part2_IdxCode_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern );
MCO_RET      Part2_IdxCode_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part2 * handle);
MCO_RET      Part2_IdxCode_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ Part2 *handle_);

/*---------------------------------------------------------------------*/
/* class User methods                                                  */

MCO_RET      User_new                                 ( mco_trans_h t, /*OUT*/ User *handle );
MCO_RET      User_delete                              ( User *handle );
MCO_RET      User_set_allocation_block_size          (mco_trans_h t, mco_size_t block_size);
MCO_RET      User_set_caching_priority               (mco_trans_h t, int priority);
MCO_RET      User_delete_all                          ( mco_trans_h t );
MCO_RET      User_checkpoint                          ( User *handle );

MCO_RET      User_broker_id_get                       ( User *handle, /*OUT*/ int4 * result);
MCO_RET      User_broker_id_put                       ( User *handle, int4 value );

MCO_RET      User_user_id_get                         ( User *handle, /*OUT*/ uint4 * result);
MCO_RET      User_user_id_put                         ( User *handle, uint4 value );

MCO_RET      User_password_get                        ( User *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      User_password_put                        ( User *handle, const char * src, uint2 len) ;

MCO_RET      User_from_cursor                         ( mco_trans_h t, mco_cursor_h c, /*OUT*/ User *handle );

MCO_RET      User_idx_user_id_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c );
MCO_RET      User_idx_user_id_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ );
MCO_RET      User_idx_user_id_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ );
MCO_RET      User_idx_user_id_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_);
MCO_RET      User_idx_user_id_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ );
MCO_RET      User_idx_user_id_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern );
MCO_RET      User_idx_user_id_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, User * handle);
MCO_RET      User_idx_user_id_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ User *handle_);

/*---------------------------------------------------------------------*/
/* class OrderInsert methods                                           */

MCO_RET      OrderInsert_new                          ( mco_trans_h t, /*OUT*/ OrderInsert *handle );
MCO_RET      OrderInsert_delete                       ( OrderInsert *handle );
MCO_RET      OrderInsert_set_allocation_block_size   (mco_trans_h t, mco_size_t block_size);
MCO_RET      OrderInsert_set_caching_priority        (mco_trans_h t, int priority);
MCO_RET      OrderInsert_delete_all                   ( mco_trans_h t );
MCO_RET      OrderInsert_checkpoint                   ( OrderInsert *handle );
MCO_RET      OrderInsert_pack                         ( OrderInsert *handle, /*OUT*/ uint4 * pages_released );

MCO_RET      OrderInsert_owner_type_get               ( OrderInsert *handle, /*OUT*/ uint2 * result);
MCO_RET      OrderInsert_owner_type_put               ( OrderInsert *handle, uint2 value );

MCO_RET      OrderInsert_front_id_get                 ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_front_id_put                 ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_session_id_get               ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_session_id_put               ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_order_ref_get                ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_order_ref_put                ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_user_id_get                  ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_user_id_put                  ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_investor_id_get              ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_investor_id_put              ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_secu_account_get             ( OrderInsert *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      OrderInsert_secu_account_put             ( OrderInsert *handle, const char * src, uint2 len) ;

MCO_RET      OrderInsert_security_code_get            ( OrderInsert *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len);
MCO_RET      OrderInsert_security_code_size           ( OrderInsert *handle, /*OUT*/ uint2 *result);
MCO_RET      OrderInsert_security_code_put            ( OrderInsert *handle, const char * src, uint2 len);

MCO_RET      OrderInsert_exchange_type_get            ( OrderInsert *handle, /*OUT*/ uint1 * result);
MCO_RET      OrderInsert_exchange_type_put            ( OrderInsert *handle, uint1 value );

MCO_RET      OrderInsert_bs_flag_get                  ( OrderInsert *handle, /*OUT*/ uint1 * result);
MCO_RET      OrderInsert_bs_flag_put                  ( OrderInsert *handle, uint1 value );

MCO_RET      OrderInsert_business_code_get            ( OrderInsert *handle, /*OUT*/ int4 * result);
MCO_RET      OrderInsert_business_code_put            ( OrderInsert *handle, int4 value );

MCO_RET      OrderInsert_price_type_get               ( OrderInsert *handle, /*OUT*/ uint1 * result);
MCO_RET      OrderInsert_price_type_put               ( OrderInsert *handle, uint1 value );

MCO_RET      OrderInsert_price_get_chars              ( OrderInsert *handle, char* buf, int buf_size);
MCO_RET      OrderInsert_price_to_chars               (mco_int8 scaled_num, char* buf, int buf_size);
MCO_RET      OrderInsert_price_put_chars              ( OrderInsert *handle, char const* buf);
MCO_RET      OrderInsert_price_from_chars             ( mco_int8* scaled_num, char const* buf);
MCO_RET      OrderInsert_price_get                    ( OrderInsert *handle, /*OUT*/ mco_int8 * result);
MCO_RET      OrderInsert_price_put                    ( OrderInsert *handle, mco_int8 value );

MCO_RET      OrderInsert_volume_get                   ( OrderInsert *handle, /*OUT*/ uint8 * result);
MCO_RET      OrderInsert_volume_put                   ( OrderInsert *handle, uint8 value );

MCO_RET      OrderInsert_from_cursor                  ( mco_trans_h t, mco_cursor_h c, /*OUT*/ OrderInsert *handle );

/*---------------------------------------------------------------------*/
/* class Order methods                                                 */

MCO_RET      Order_new                              ( mco_trans_h t, /*OUT*/ Order *handle );
MCO_RET      Order_delete                           ( Order *handle );
MCO_RET      Order_set_allocation_block_size       (mco_trans_h t, mco_size_t block_size);
MCO_RET      Order_set_caching_priority            (mco_trans_h t, int priority);
MCO_RET      Order_delete_all                       ( mco_trans_h t );
MCO_RET      Order_checkpoint                       ( Order *handle );
MCO_RET      Order_pack                             ( Order *handle, /*OUT*/ uint4 * pages_released );

MCO_RET      Order_owner_type_get                   ( Order *handle, /*OUT*/ uint2 * result);
MCO_RET      Order_owner_type_put                   ( Order *handle, uint2 value );

MCO_RET      Order_front_id_get                     ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_front_id_put                     ( Order *handle, int4 value );

MCO_RET      Order_session_id_get                   ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_session_id_put                   ( Order *handle, int4 value );

MCO_RET      Order_order_ref_get                    ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_order_ref_put                    ( Order *handle, int4 value );

MCO_RET      Order_user_id_get                      ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_user_id_put                      ( Order *handle, int4 value );

MCO_RET      Order_investor_id_get                  ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_investor_id_put                  ( Order *handle, int4 value );

MCO_RET      Order_secu_account_get                 ( Order *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      Order_secu_account_put                 ( Order *handle, const char * src, uint2 len) ;

MCO_RET      Order_security_code_get                ( Order *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len);
MCO_RET      Order_security_code_size               ( Order *handle, /*OUT*/ uint2 *result);
MCO_RET      Order_security_code_put                ( Order *handle, const char * src, uint2 len);

MCO_RET      Order_exchange_type_get                ( Order *handle, /*OUT*/ uint1 * result);
MCO_RET      Order_exchange_type_put                ( Order *handle, uint1 value );

MCO_RET      Order_bs_flag_get                      ( Order *handle, /*OUT*/ uint1 * result);
MCO_RET      Order_bs_flag_put                      ( Order *handle, uint1 value );

MCO_RET      Order_business_code_get                ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_business_code_put                ( Order *handle, int4 value );

MCO_RET      Order_price_type_get                   ( Order *handle, /*OUT*/ uint1 * result);
MCO_RET      Order_price_type_put                   ( Order *handle, uint1 value );

MCO_RET      Order_price_get_chars                  ( Order *handle, char* buf, int buf_size);
MCO_RET      Order_price_to_chars                   (mco_int8 scaled_num, char* buf, int buf_size);
MCO_RET      Order_price_put_chars                  ( Order *handle, char const* buf);
MCO_RET      Order_price_from_chars                 ( mco_int8* scaled_num, char const* buf);
MCO_RET      Order_price_get                        ( Order *handle, /*OUT*/ mco_int8 * result);
MCO_RET      Order_price_put                        ( Order *handle, mco_int8 value );

MCO_RET      Order_volume_get                       ( Order *handle, /*OUT*/ uint8 * result);
MCO_RET      Order_volume_put                       ( Order *handle, uint8 value );

MCO_RET      Order_branch_id_get                    ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_branch_id_put                    ( Order *handle, int4 value );

MCO_RET      Order_pbu_id_get                       ( Order *handle, /*OUT*/ int4 * result);
MCO_RET      Order_pbu_id_put                       ( Order *handle, int4 value );

MCO_RET      Order_order_sys_id_get                 ( Order *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      Order_order_sys_id_put                 ( Order *handle, const char * src, uint2 len) ;

MCO_RET      Order_order_exchange_id_get            ( Order *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      Order_order_exchange_id_put            ( Order *handle, const char * src, uint2 len) ;

MCO_RET      Order_status_get                       ( Order *handle, /*OUT*/ uint1 * result);
MCO_RET      Order_status_put                       ( Order *handle, uint1 value );

MCO_RET      Order_volume_traded_get                ( Order *handle, /*OUT*/ uint8 * result);
MCO_RET      Order_volume_traded_put                ( Order *handle, uint8 value );

MCO_RET      Order_amount_traded_get_chars          ( Order *handle, char* buf, int buf_size);
MCO_RET      Order_amount_traded_to_chars           (mco_int8 scaled_num, char* buf, int buf_size);
MCO_RET      Order_amount_traded_put_chars          ( Order *handle, char const* buf);
MCO_RET      Order_amount_traded_from_chars         ( mco_int8* scaled_num, char const* buf);
MCO_RET      Order_amount_traded_get                ( Order *handle, /*OUT*/ mco_int8 * result);
MCO_RET      Order_amount_traded_put                ( Order *handle, mco_int8 value );

MCO_RET      Order_from_cursor                      ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Order *handle );

/*---------------------------------------------------------------------*/
/* class OrderAction methods                                           */

MCO_RET      OrderAction_new                              ( mco_trans_h t, /*OUT*/ OrderAction *handle );
MCO_RET      OrderAction_delete                           ( OrderAction *handle );
MCO_RET      OrderAction_set_allocation_block_size       (mco_trans_h t, mco_size_t block_size);
MCO_RET      OrderAction_set_caching_priority            (mco_trans_h t, int priority);
MCO_RET      OrderAction_delete_all                       ( mco_trans_h t );
MCO_RET      OrderAction_checkpoint                       ( OrderAction *handle );
MCO_RET      OrderAction_pack                             ( OrderAction *handle, /*OUT*/ uint4 * pages_released );

MCO_RET      OrderAction_owner_type_get                   ( OrderAction *handle, /*OUT*/ uint2 * result);
MCO_RET      OrderAction_owner_type_put                   ( OrderAction *handle, uint2 value );

MCO_RET      OrderAction_user_id_get                      ( OrderAction *handle, /*OUT*/ int4 * result);
MCO_RET      OrderAction_user_id_put                      ( OrderAction *handle, int4 value );

MCO_RET      OrderAction_investor_id_get                  ( OrderAction *handle, /*OUT*/ int4 * result);
MCO_RET      OrderAction_investor_id_put                  ( OrderAction *handle, int4 value );

MCO_RET      OrderAction_front_id_get                     ( OrderAction *handle, /*OUT*/ int4 * result);
MCO_RET      OrderAction_front_id_put                     ( OrderAction *handle, int4 value );

MCO_RET      OrderAction_session_id_get                   ( OrderAction *handle, /*OUT*/ int4 * result);
MCO_RET      OrderAction_session_id_put                   ( OrderAction *handle, int4 value );

MCO_RET      OrderAction_order_ref_get                    ( OrderAction *handle, /*OUT*/ int4 * result);
MCO_RET      OrderAction_order_ref_put                    ( OrderAction *handle, int4 value );

MCO_RET      OrderAction_order_sys_id_get                 ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      OrderAction_order_sys_id_put                 ( OrderAction *handle, const char * src, uint2 len) ;

MCO_RET      OrderAction_exchange_type_get                ( OrderAction *handle, /*OUT*/ uint1 * result);
MCO_RET      OrderAction_exchange_type_put                ( OrderAction *handle, uint1 value );

MCO_RET      OrderAction_order_exchange_id_get            ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      OrderAction_order_exchange_id_put            ( OrderAction *handle, const char * src, uint2 len) ;

MCO_RET      OrderAction_secu_account_get                 ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size);
MCO_RET      OrderAction_secu_account_put                 ( OrderAction *handle, const char * src, uint2 len) ;

MCO_RET      OrderAction_security_code_get                ( OrderAction *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len);
MCO_RET      OrderAction_security_code_size               ( OrderAction *handle, /*OUT*/ uint2 *result);
MCO_RET      OrderAction_security_code_put                ( OrderAction *handle, const char * src, uint2 len);

MCO_RET      OrderAction_bs_flag_get                      ( OrderAction *handle, /*OUT*/ uint1 * result);
MCO_RET      OrderAction_bs_flag_put                      ( OrderAction *handle, uint1 value );

MCO_RET      OrderAction_volume_get                       ( OrderAction *handle, /*OUT*/ uint8 * result);
MCO_RET      OrderAction_volume_put                       ( OrderAction *handle, uint8 value );

MCO_RET      OrderAction_price_get_chars                  ( OrderAction *handle, char* buf, int buf_size);
MCO_RET      OrderAction_price_to_chars                   (mco_int8 scaled_num, char* buf, int buf_size);
MCO_RET      OrderAction_price_put_chars                  ( OrderAction *handle, char const* buf);
MCO_RET      OrderAction_price_from_chars                 ( mco_int8* scaled_num, char const* buf);
MCO_RET      OrderAction_price_get                        ( OrderAction *handle, /*OUT*/ mco_int8 * result);
MCO_RET      OrderAction_price_put                        ( OrderAction *handle, mco_int8 value );

MCO_RET      OrderAction_from_cursor                      ( mco_trans_h t, mco_cursor_h c, /*OUT*/ OrderAction *handle );

/*---------------------------------------------------------------------*/
/* struct Dimensions methods                                           */


MCO_RET      Dimensions_width_get             ( Dimensions *handle, /*OUT*/ float * result);
MCO_RET      Dimensions_width_put             ( Dimensions *handle, float value );

MCO_RET      Dimensions_length_get            ( Dimensions *handle, /*OUT*/ float * result);
MCO_RET      Dimensions_length_put            ( Dimensions *handle, float value );

MCO_RET      Dimensions_height_get            ( Dimensions *handle, /*OUT*/ float * result);
MCO_RET      Dimensions_height_put            ( Dimensions *handle, float value );
MCO_RET      Dimensions_fixed_get             ( Dimensions *handle_, Dimensions_fixed* dst_ );
MCO_RET      Dimensions_fixed_put             ( Dimensions *handle_, Dimensions_fixed const* src_ );
MCO_RET      A_fixed_get                     ( A *handle_, A_fixed* dst_ );
MCO_RET      A_fixed_put                     ( A *handle_, A_fixed const* src_ );
MCO_RET      B_fixed_get                     ( B *handle_, B_fixed* dst_ );
MCO_RET      B_fixed_put                     ( B *handle_, B_fixed const* src_ );
MCO_RET      Part_fixed_get                     ( Part *handle_, Part_fixed* dst_ );
MCO_RET      Part_fixed_put                     ( Part *handle_, Part_fixed const* src_ );
MCO_RET      Part2_fixed_get                       ( Part2 *handle_, Part2_fixed* dst_ );
MCO_RET      Part2_fixed_put                       ( Part2 *handle_, Part2_fixed const* src_ );
MCO_RET      User_fixed_get                           ( User *handle_, User_fixed* dst_ );
MCO_RET      User_fixed_put                           ( User *handle_, User_fixed const* src_ );
MCO_RET      OrderInsert_fixed_get                    ( OrderInsert *handle_, OrderInsert_fixed* dst_ );
MCO_RET      OrderInsert_fixed_put                    ( OrderInsert *handle_, OrderInsert_fixed const* src_ );
MCO_RET      Order_fixed_get                        ( Order *handle_, Order_fixed* dst_ );
MCO_RET      Order_fixed_put                        ( Order *handle_, Order_fixed const* src_ );
MCO_RET      OrderAction_fixed_get                        ( OrderAction *handle_, OrderAction_fixed* dst_ );
MCO_RET      OrderAction_fixed_put                        ( OrderAction *handle_, OrderAction_fixed const* src_ );

#ifdef __cplusplus
#ifdef MCO_CPP_INTERFACE
} // namespace genericdb
#endif
} // extern "C" 
#endif

#endif
