/* Generated by eXtremeDB Schema Compiler, build 1797, rev. stable, rev. 23320
 * at Tue Jan  1 23:28:18 2019
 */

#include "genericdb.h"
#include "mcowrap.h"


/*---------------------------------------------------------------------*/
/* calculator                                                          */

mco_calculator_h genericdb_get_calculator(void)
{
  return (mco_calculator_h)NULLPTR;
}


/*---------------------------------------------------------------------*/
/* dictionary                                                          */

static mco_dictionary_t  dict; 
mco_dictionary_h genericdb_get_dictionary(void)
{ 
  static int dictionary_ready = 0; 

  if( ! dictionary_ready ) 
  {
    static mco_dict_field_t v_field_info[17] = { 
    /* Dimensions */
    {"height", {4, 4, 4, 4, 4, 4}, 10, 0, 0, -1, 4, -1, 0, 2, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    {"length", {4, 4, 0, 4, 4, 0}, 10, 0, 0, -1, 4, -1, 0, 1, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    {"width", {4, 4, 8, 4, 4, 8}, 10, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 3 */},
    /* A */
    {"ui4", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 1 */},
    /* B */
    {"ui4", {4, 4, 0, 4, 4, 0}, 3, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 2 */},
    /* Part */
    {"code", {4, 4, 44, 4, 4, 8}, 3, 8, 0, -1, 4, -1, 0, 3, 3, 65535, 65535, 0, 0, 0 /* 7 */},
    {"dim", {12, 4, 48, 12, 4, 12}, 50, 0, 0, 0, 0, -1, 0, 4, 4, 65535, 65535, 0, 0, 0 /* 8 */},
    {"name", {2, 2, 60, 4, 4, 0}, 8, 8, 0, -1, 0, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 5 */},
    {"options", {40, 4, 0, 40, 4, 24}, 3, 2, 10, -1, 4, -1, 0, 5, 5, 65535, 65535, 0, 0, 0 /* 9 */},
    {"price", {4, 4, 40, 4, 4, 4}, 10, 0, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 6 */},
    {"type", {2, 2, 62, 4, 4, 64}, 8, 8, 0, -1, 0, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 4 */},
    /* Part2 */
    {"broker_id", {4, 4, 0, 4, 4, 0}, 6, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 10 */},
    {"password", {8, 1, 8, 8, 1, 8}, 7, 0, 0, -1, 8, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 11 */},
    {"user_id", {4, 4, 4, 4, 4, 4}, 3, 8, 0, -1, 4, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 12 */},
    /* User */
    {"broker_id", {4, 4, 4, 4, 4, 4}, 6, 0, 0, -1, 4, -1, 0, 0, 0, 65535, 65535, 0, 0, 0 /* 13 */},
    {"password", {8, 1, 8, 8, 1, 8}, 7, 0, 0, -1, 8, -1, 0, 2, 2, 65535, 65535, 0, 0, 0 /* 15 */},
    {"user_id", {4, 4, 0, 4, 4, 0}, 3, 8, 0, -1, 4, -1, 0, 1, 1, 65535, 65535, 0, 0, 0 /* 14 */}
    };

    static mco_dict_struct_t v_struct_info[6] = { 
    { "Dimensions", 0, 3, (v_field_info + 0), 12, 4, 12, 4 },
    { "A", 0, 1, (v_field_info + 3), 4, 4, 4, 4 },
    { "B", 0, 1, (v_field_info + 4), 4, 4, 4, 4 },
    { "Part", 1, 6, (v_field_info + 5), 64, 4, 68, 4 },
    { "Part2", 0, 3, (v_field_info + 11), 16, 4, 16, 4 },
    { "User", 0, 3, (v_field_info + 14), 16, 4, 16, 4 }
    };

    dictionary_ready = 1;

    {
      static const char * v_class_names[] = 
      {
        0, 
        "A"           , /* [1] */
        "B"           , /* [2] */
        "Part"        , /* [3] */
        "Part2"       , /* [4] */
        "User"        , /* [5] */
        0
      };

      dict.str_class_names = v_class_names;
    }


    {
      static const char * v_index_names[] = 
      {
        "A.list_index_"           , /* [0] */
        "B.list_index_"           , /* [1] */
        "Part.ByCode"             , /* [2] */
        "Part.ByType"             , /* [3] */
        "Part.IdxCode"            , /* [4] */
        "Part2.IdxCode"           , /* [5] */
        "User.idx_user_id"        , /* [6] */
        0
      };

      dict.str_index_names = v_index_names;
    }

    {
      static  mco_dict_class_info_t class_inf[6] = { 
        { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, 
        { 0, 0, 0, -1, 4, 0, -1, 0, 0, -1, -2, 17, (v_struct_info + 1), 4, 0, 0 }  /* A */ , 
        { 1, 1, 1, -1, 4, 0, -1, 0, 0, -1, -2, 49, (v_struct_info + 2), 4, 0, 0 }  /* B */ , 
        { 2, 4, -1, -1, 0, 0, -1, 0, 0, -1, -2, 0, (v_struct_info + 3), 68, 0, 0 }  /* Part */ , 
        { 5, 5, -1, -1, 16, 0, -1, 0, 0, -1, -2, 16, (v_struct_info + 4), 16, 0, 0 }  /* Part2 */ , 
        { 6, 6, -1, -1, 16, 0, -1, 0, 0, -1, -2, 16, (v_struct_info + 5), 16, 0, 0 }  /* User */ 
      };
      dict.v_class_info = class_inf;
    }


    dict.v_desc_events = (mco_dict_event_t *)0;
    

    dict.v_all_struct = v_struct_info;
    {
      static mco_dict_index_field_t v_all_index_fields[ 6] = {
          { 8, -1, 4294967295U, 4, 3, 0, 3, -1 } /* [0] */
        , { 64, -1, 4294967295U, 0, 8, 0, 0, -1 } /* [1] */
        , { 0, -1, 4294967295U, 0, 8, 0, 1, -1 } /* [2] */
        , { 8, -1, 4294967295U, 4, 3, 0, 3, -1 } /* [3] */
        , { 4, -1, 4294967295U, 4, 3, 0, 2, -1 } /* [4] */
        , { 0, -1, 4294967295U, 4, 3, 0, 1, -1 } /* [5] */
      }; 

      static mco_dict_index_t v_all_indexes_info[ 7] = {
          { 1, 1, 0, -1, 1028, & v_all_index_fields[0], 0, -1 } /* A.list_index_ [0] */
        , { 2, 2, 0, -1, 1060, & v_all_index_fields[0], 0, -1 } /* B.list_index_ [1] */
        , { 3, 3, 1, -1, 2052, & v_all_index_fields[0], 10000, -1 } /* Part.ByCode [2] */
        , { 3, 1, 2, -1, 2048, & v_all_index_fields[1], 0, -1 } /* Part.ByType [3] */
        , { 3, 1, 1, -1, 2052, & v_all_index_fields[3], 0, -1 } /* Part.IdxCode [4] */
        , { 4, 1, 1, -1, 2052, & v_all_index_fields[4], 0, -1 } /* Part2.IdxCode [5] */
        , { 5, 1, 1, -1, 2052, & v_all_index_fields[5], 0, -1 } /* User.idx_user_id [6] */
      }; 

      dict.v_desc_indexes = v_all_indexes_info;
    }


    dict.v_desc_colls = (mco_dict_collation_t *)0;
    
    dict.version_major             = 8;
    dict.version_minor             = 0;
    dict.version_build             = 1797;
    dict.magic_number              = 9;
    dict.oid_is_supported          = 0;
    dict.auto_oid_supported        = 0;
    dict.flags                     = 0;
    dict.n_class_codes             = 5;
    dict.n_list_indexes            = 2;
    dict.n_autoid_indexes          = 0;
    dict.n_history_indexes         = 0;
    dict.n_userdef_indexes         = 0;
    dict.n_desc_indexes            = 7;
    dict.n_desc_events             = 0;
    dict.n_desc_colls              = 0;
    dict.n_structs                 = 6;
    dict.num_oid_estimation        = 0;
    dict.num_HA_estimation         = 0;
    dict.max_numof_indexes_per_obj = 3;
    dict.exact_OID_sizeof          = 0;
    dict.layout_OID_size           = 0;
    dict.sizeof_mco_offs_t[0]      = 4;
    dict.sizeof_mco_offs_t[1]      = sizeof(mco_offs_t);
    dict.sizeof_mco_size_t[0]      = 4;
    dict.sizeof_mco_size_t[1]      = sizeof(mco_size_t);
    dict.init_i_data.ptr           = 0;
    dict.init_i_data_n             = 0;
    dict.init_d_data.ptr           = 0;
    dict.init_d_data_n             = 0;
  }

  return &dict; 
}

MCO_RET      A_new                           ( mco_trans_h t, /*OUT*/ A *handle )
{ return mco_w_new_obj_noid( t, 4, 1, (mco_objhandle_h)handle);
}

MCO_RET      A_delete                        ( A *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      A_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 1 ); 
}

MCO_RET      A_checkpoint                    ( A *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      A_ui4_get                       ( A *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      A_ui4_put                       ( A *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      A_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ A *handle )
{ return mco_w_obj_from_cursor( t, c, 1, (mco_objhandle_h)handle ); 
}

MCO_RET      A_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_list_cursor( t, 1, c );
}

MCO_RET      B_new                           ( mco_trans_h t, /*OUT*/ B *handle )
{ return mco_w_new_obj_noid( t, 4, 2, (mco_objhandle_h)handle);
}

MCO_RET      B_delete                        ( B *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      B_set_allocation_block_size    (mco_trans_h t, mco_size_t block_size)
{ return mco_set_class_allocation_block_size(t, 2, block_size); 
}

MCO_RET      B_set_caching_priority         (mco_trans_h t, int priority)
{ return mco_set_class_caching_priority(t, 2, priority); 
}

MCO_RET      B_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 2 ); 
}

MCO_RET      B_checkpoint                    ( B *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      B_ui4_get                       ( B *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      B_ui4_put                       ( B *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      B_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ B *handle )
{ return mco_w_obj_from_cursor( t, c, 2, (mco_objhandle_h)handle ); 
}

MCO_RET      B_list_cursor                   ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_list_cursor( t, 2, c );
}

MCO_RET      Part_new                           ( mco_trans_h t, /*OUT*/ Part *handle )
{ return mco_w_new_obj_noid( t, 68, 3, (mco_objhandle_h)handle);
}

MCO_RET      Part_delete                        ( Part *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      Part_delete_all                    ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 3 ); 
}

MCO_RET      Part_checkpoint                    ( Part *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      Part_pack                          ( Part *handle, /*OUT*/ uint4 * pages_released )
{ return mco_w_compact( (mco_objhandle_h)handle, 3, 3, pages_released); 
}

MCO_RET      Part_type_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 64, 62, 0, dest, dest_size, len); 
}

MCO_RET      Part_type_size                     ( Part *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 64, 62, 0, result); 
}

MCO_RET      Part_type_put                      ( Part *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 64, 62, 0, src, len, 1);
}

MCO_RET      Part_name_get                      ( Part *handle, /*OUT*/ char * dest, uint2 dest_size, /*OUT*/ uint2 * len)
{ return mco_w_string_get2( (mco_objhandle_h) handle, 0, 60, 1, dest, dest_size, len); 
}

MCO_RET      Part_name_size                     ( Part *handle, /*OUT*/ uint2 *result)
{ return mco_w_string_len2( (mco_objhandle_h) handle, 0, 60, 1, result); 
}

MCO_RET      Part_name_put                      ( Part *handle, const char * src, uint2 len)
{ return mco_w_string_put2( (mco_objhandle_h) handle, 0, 60, 1, src, len, 1);
}

MCO_RET      Part_price_get                     ( Part *handle, /*OUT*/ float * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 4, 40, 2,result);
}

MCO_RET      Part_price_put                     ( Part *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put2( (mco_objhandle_h) handle, 4, 40, 2, 0, u.i); }
}

MCO_RET      Part_code_get                      ( Part *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get2( (mco_objhandle_h) handle, 8, 44, 3,result);
}

MCO_RET      Part_code_put                      ( Part *handle, uint4 value )
{ return mco_w_b4_put2( (mco_objhandle_h) handle, 8, 44, 3, 1, (uint4) value);
}

MCO_RET      Part_dim_read_handle               ( Part *handle, /*OUT*/ Dimensions * h )
{ return mco_w_struct_get2( (mco_objhandle_h)handle, (mco_objhandle_h)h, 12, 48, 4); 
}

MCO_RET      Part_dim_write_handle              ( Part *handle, /*OUT*/ Dimensions * h )
{ return mco_w_struct_put2( (mco_objhandle_h)handle, (mco_objhandle_h)h, 12, 48, 4, 0);
}

MCO_RET      Part_options_at                    ( Part *handle, uint2 index, /*OUT*/ uint4 *result)
{ return mco_w_va_simple_e_get2( (mco_objhandle_h)handle, 24, 0, 5, index, 4, result, 10);
}

MCO_RET      Part_options_get_range             ( Part *handle, uint2 start_index, uint2 num, /*OUT*/ uint4 *dest )
{ return mco_w_va_simple_e_getrange2( (mco_objhandle_h)handle, 24, 0, 5, start_index, 4, num, dest, 10, 0);
}

MCO_RET      Part_options_put                   ( Part *handle, uint2 index, uint4 value )
{ return mco_w_va_simple_e_put2( (mco_objhandle_h)handle, 24, 0, 5, index, 4, 0, &value, 10);
}

MCO_RET      Part_options_put_range             ( Part *handle, uint2 start_index, uint2 num, const uint4 *src )
{ return mco_w_va_simple_e_putrange2( (mco_objhandle_h)handle, 24, 0, 5, start_index, 4, num, 0, src, 10, 0);
}

MCO_RET      Part_from_cursor                   ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part *handle )
{ return mco_w_obj_from_cursor( t, c, 3, (mco_objhandle_h)handle ); 
}

MCO_RET      Part_ByCode_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 2, c );
}

MCO_RET      Part_ByCode_compare                ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_ByCode_find                   ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_hash_find_scalar(t, 2, a_, (mco_objhandle_h)handle_);
}

MCO_RET      Part_ByType_index_cursor           ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 3, c );
}

MCO_RET      Part_ByType_search                 ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part_ByType_compare                ( mco_trans_h t, mco_cursor_h c, const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_ByType_pattern_size           ( const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [3];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part_ByType_pattern_search         ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , const char *type_key_, uint2 sizeof_type_key_, const char *name_key_, uint2 sizeof_name_key_ )
{ mco_external_field_t a_ [3];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_type_key_; pa_->ptr = type_key_; pa_++; 
  pa_->field_type = 8; pa_->v.ptr_size = sizeof_name_key_; pa_->ptr = name_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part_ByType_pattern_next           ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part_ByType_locate                 ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle)
{ return mco_w_cursor_locate( t, 3, (mco_objhandle_h)handle, c);
}

MCO_RET      Part_IdxCode_index_cursor          ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 4, c );
}

MCO_RET      Part_IdxCode_search                ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 code_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part_IdxCode_compare               ( mco_trans_h t, mco_cursor_h c, uint4 code_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part_IdxCode_pattern_size          ( uint4 code_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part_IdxCode_pattern_search        ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 code_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part_IdxCode_pattern_next          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part_IdxCode_locate                ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part * handle)
{ return mco_w_cursor_locate( t, 4, (mco_objhandle_h)handle, c);
}

MCO_RET      Part_IdxCode_find                  ( mco_trans_h t, uint4 code_key_, /*OUT*/ Part *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = code_key_; 
  return mco_w_tree_find_scalar(t, 4, a_, (mco_objhandle_h)handle_);
}

MCO_RET      Part2_new                             ( mco_trans_h t, /*OUT*/ Part2 *handle )
{ return mco_w_new_obj_noid( t, 16, 4, (mco_objhandle_h)handle);
}

MCO_RET      Part2_delete                          ( Part2 *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      Part2_delete_all                      ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 4 ); 
}

MCO_RET      Part2_checkpoint                      ( Part2 *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      Part2_broker_id_get                   ( Part2 *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      Part2_broker_id_put                   ( Part2 *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, (uint4) value);
}

MCO_RET      Part2_password_get                    ( Part2 *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get( (mco_objhandle_h) handle, 8, 1, dest, dest_size, 8);
}

MCO_RET      Part2_password_put                    ( Part2 *handle, const char * src, uint2 len) 
{ return mco_w_chars_put( (mco_objhandle_h)handle, 8, 1, src, len, 8, 0);
}

MCO_RET      Part2_user_id_get                     ( Part2 *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 2, result);
}

MCO_RET      Part2_user_id_put                     ( Part2 *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 4, 2, 1, (uint4) value);
}

MCO_RET      Part2_from_cursor                     ( mco_trans_h t, mco_cursor_h c, /*OUT*/ Part2 *handle )
{ return mco_w_obj_from_cursor( t, c, 4, (mco_objhandle_h)handle ); 
}

MCO_RET      Part2_IdxCode_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 5, c );
}

MCO_RET      Part2_IdxCode_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      Part2_IdxCode_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      Part2_IdxCode_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      Part2_IdxCode_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      Part2_IdxCode_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      Part2_IdxCode_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, Part2 * handle)
{ return mco_w_cursor_locate( t, 5, (mco_objhandle_h)handle, c);
}

MCO_RET      Part2_IdxCode_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ Part2 *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_tree_find_scalar(t, 5, a_, (mco_objhandle_h)handle_);
}

MCO_RET      User_new                                 ( mco_trans_h t, /*OUT*/ User *handle )
{ return mco_w_new_obj_noid( t, 16, 5, (mco_objhandle_h)handle);
}

MCO_RET      User_delete                              ( User *handle )
{ return mco_w_obj_delete( (mco_objhandle_h)handle); 
}

MCO_RET      User_delete_all                          ( mco_trans_h t )
{ return mco_w_obj_delete_all( t, 5 ); 
}

MCO_RET      User_checkpoint                          ( User *handle )
{ return mco_w_obj_checkpoint( (mco_objhandle_h)handle );
}

MCO_RET      User_broker_id_get                       ( User *handle, /*OUT*/ int4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 0, result);
}

MCO_RET      User_broker_id_put                       ( User *handle, int4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 4, 0, 0, (uint4) value);
}

MCO_RET      User_user_id_get                         ( User *handle, /*OUT*/ uint4 * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 1, result);
}

MCO_RET      User_user_id_put                         ( User *handle, uint4 value )
{ return mco_w_b4_put( (mco_objhandle_h) handle, 0, 1, 1, (uint4) value);
}

MCO_RET      User_password_get                        ( User *handle, /*OUT*/ char * dest, uint2 dest_size)
{ return mco_w_chars_get( (mco_objhandle_h) handle, 8, 2, dest, dest_size, 8);
}

MCO_RET      User_password_put                        ( User *handle, const char * src, uint2 len) 
{ return mco_w_chars_put( (mco_objhandle_h)handle, 8, 2, src, len, 8, 0);
}

MCO_RET      User_from_cursor                         ( mco_trans_h t, mco_cursor_h c, /*OUT*/ User *handle )
{ return mco_w_obj_from_cursor( t, c, 5, (mco_objhandle_h)handle ); 
}

MCO_RET      User_idx_user_id_index_cursor            ( mco_trans_h t, /*OUT*/ mco_cursor_h c )
{ return mco_w_index_cursor( t, 6, c );
}

MCO_RET      User_idx_user_id_search                  ( mco_trans_h t, /*INOUT*/ mco_cursor_h c, MCO_OPCODE op_, uint4 user_id_key_ )
{ mco_external_field_t a_ [1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 

  return mco_w_tree_find(t,c,op_,a_);
}

MCO_RET      User_idx_user_id_compare                 ( mco_trans_h t, mco_cursor_h c, uint4 user_id_key_, /*OUT*/ int *result_ )
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_cursor_compare( t, c, a_, result_);
}

MCO_RET      User_idx_user_id_pattern_size            ( uint4 user_id_key_, /*OUT*/ uint4 *size_)
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
   return mco_pattern_size( a_,size_);
}

MCO_RET      User_idx_user_id_pattern_search          ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern, mco_size_t memsize , uint4 user_id_key_ )
{ mco_external_field_t a_ [2];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  (pa_+1)->field_type=0;
  return mco_pattern_search(t, c, allocated_pattern, memsize, a_);
}

MCO_RET      User_idx_user_id_pattern_next            ( mco_trans_h t, mco_cursor_h c, /*INOUT*/ void *allocated_pattern )
{ return mco_pattern_next(t, c , allocated_pattern,  0);
}

MCO_RET      User_idx_user_id_locate                  ( mco_trans_h t, /*OUT*/ mco_cursor_h c, User * handle)
{ return mco_w_cursor_locate( t, 6, (mco_objhandle_h)handle, c);
}

MCO_RET      User_idx_user_id_find                    ( mco_trans_h t, uint4 user_id_key_, /*OUT*/ User *handle_)
{ mco_external_field_t a_[1];
  mco_external_field_h pa_ = a_;
  pa_->field_type = 3; pa_->v.u4 = user_id_key_; 
  return mco_w_tree_find_scalar(t, 6, a_, (mco_objhandle_h)handle_);
}

MCO_RET      Dimensions_width_get             ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 8, 0, result);
}

MCO_RET      Dimensions_width_put             ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 8, 0, 0, u.i); }
}

MCO_RET      Dimensions_length_get            ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 0, 0, result);
}

MCO_RET      Dimensions_length_put            ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 0, 0, 0, u.i); }
}

MCO_RET      Dimensions_height_get            ( Dimensions *handle, /*OUT*/ float * result)
{ return mco_w_b4_get( (mco_objhandle_h) handle, 4, 0, result);
}

MCO_RET      Dimensions_height_put            ( Dimensions *handle, float value )
{{ union { float f; uint4 i; } u; u.f = value; return mco_w_b4_put( (mco_objhandle_h) handle, 4, 0, 0, u.i); }
}

MCO_RET      Dimensions_fixed_get             ( Dimensions *handle_, Dimensions_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = Dimensions_width_get(handle_, &dst_->width)) == MCO_S_OK &&
    (rc_ = Dimensions_length_get(handle_, &dst_->length)) == MCO_S_OK &&
    (rc_ = Dimensions_height_get(handle_, &dst_->height)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Dimensions_fixed_put             ( Dimensions *handle_, Dimensions_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = Dimensions_width_put(handle_, src_->width)) == MCO_S_OK &&
    (rc_ = Dimensions_length_put(handle_, src_->length)) == MCO_S_OK &&
    (rc_ = Dimensions_height_put(handle_, src_->height)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      A_fixed_get                     ( A *handle_, A_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = A_ui4_get(handle_, &dst_->ui4)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      A_fixed_put                     ( A *handle_, A_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = A_ui4_put(handle_, src_->ui4)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      B_fixed_get                     ( B *handle_, B_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = B_ui4_get(handle_, &dst_->ui4)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      B_fixed_put                     ( B *handle_, B_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = B_ui4_put(handle_, src_->ui4)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      Part_fixed_get                     ( Part *handle_, Part_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  Dimensions dim;
  return
    (rc_ = Part_price_get(handle_, &dst_->price)) == MCO_S_OK &&
    (rc_ = Part_code_get(handle_, &dst_->code)) == MCO_S_OK &&
    (rc_ = Part_dim_read_handle(handle_, &dim)) == MCO_S_OK && ((rc_ = Dimensions_fixed_get(&dim, &dst_->dim)) == MCO_S_OK || (has_nulls_ = rc_) == MCO_S_NULL_VALUE) &&
    (rc_ = Part_options_get_range(handle_, 0, 10, dst_->options)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Part_fixed_put                     ( Part *handle_, Part_fixed const* src_ )
{ MCO_RET rc_;
  Dimensions dim;
  return
    (rc_ = Part_price_put(handle_, src_->price)) == MCO_S_OK &&
    (rc_ = Part_code_put(handle_, src_->code)) == MCO_S_OK &&
    (rc_ = Part_dim_write_handle(handle_, &dim)) == MCO_S_OK && (rc_ = Dimensions_fixed_put(&dim, &src_->dim)) == MCO_S_OK &&
    (rc_ = Part_options_put_range(handle_, 0, 10, src_->options)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      Part2_fixed_get                       ( Part2 *handle_, Part2_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = Part2_broker_id_get(handle_, &dst_->broker_id)) == MCO_S_OK &&
    (rc_ = Part2_password_get(handle_, dst_->password, 8)) == MCO_S_OK &&
    (rc_ = Part2_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      Part2_fixed_put                       ( Part2 *handle_, Part2_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = Part2_broker_id_put(handle_, src_->broker_id)) == MCO_S_OK &&
    (rc_ = Part2_password_put(handle_, src_->password, 8)) == MCO_S_OK &&
    (rc_ = Part2_user_id_put(handle_, src_->user_id)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

MCO_RET      User_fixed_get                           ( User *handle_, User_fixed* dst_ )
{ MCO_RET rc_ = MCO_S_OK, has_nulls_ = MCO_S_OK;
  return
    (rc_ = User_broker_id_get(handle_, &dst_->broker_id)) == MCO_S_OK &&
    (rc_ = User_user_id_get(handle_, &dst_->user_id)) == MCO_S_OK &&
    (rc_ = User_password_get(handle_, dst_->password, 8)) == MCO_S_OK
  ? has_nulls_ : rc_;
}

MCO_RET      User_fixed_put                           ( User *handle_, User_fixed const* src_ )
{ MCO_RET rc_;
  return
    (rc_ = User_broker_id_put(handle_, src_->broker_id)) == MCO_S_OK &&
    (rc_ = User_user_id_put(handle_, src_->user_id)) == MCO_S_OK &&
    (rc_ = User_password_put(handle_, src_->password, 8)) == MCO_S_OK
  ? MCO_S_OK : rc_;
}

