#ifndef FTD_ERRORS_H_
#define FTD_ERRORS_H_

#define FTD_ERROR_CODE_TRANSACTION_ERROR 0x0001
#define FTD_ERROR_TEXT_TRANSACTION_ERROR "事务打开错误"

#define FTD_ERROR_CODE_USER_ID_NOT_EXIST 0x0101
#define FTD_ERROR_TEXT_USER_ID_NOT_EXIST "用户代码不存在"

#define FTD_ERROR_CODE_PASSWORD_ERROR  0x0102
#define FTD_ERROR_TEXT_PASSWORD_ERROR  "用户密码错误"

#define FTD_ERROR_CODE_AUTHORIZATION_DENIED 0x0103
#define FTD_ERROR_TEXT_AUTHORIZATION_DENIED "登录权限不足"

#endif